# -*- coding: utf-8 -*-
# Ghidra script for the SMBW Archipelago project — RE annotation export.
#
# The INVERSE of import_sdk_symbols.py.  That script imports Nintendo's
# symbol maps INTO Ghidra; this one exports OUR discoveries (the
# functions/labels we renamed, the structs we defined, the plate
# comments we wrote) back OUT to checked-in repo files, so the analysis
# survives the local .gpr project (machine change, project corruption,
# teammate handoff).
#
# Outputs (both under switch-mod/syms/100/):
#
#   re_discovered.sym   — user-named functions/labels in the same
#                         `name = __main_start + 0xOFFSET;` format
#                         import_sdk_symbols.py already parses.  This
#                         CLOSES THE LOOP: re-running the importer on a
#                         fresh Ghidra load reapplies every name here.
#
#   re_structs.json     — user-defined struct/datatype layouts (field
#                         offset / type / name) plus function plate
#                         comments.  Human- and machine-readable; not
#                         consumed by the importer (Ghidra struct import
#                         is a separate step), but the durable record of
#                         the layout work in §4 of smbw-re-map.md.
#
# What is SKIPPED on the .sym side (so the file stays OUR discoveries,
# not a re-dump of what we already import):
#   - Ghidra default names: FUN_*, LAB_*, DAT_*, SUB_*, UNK_*, switchD_*
#   - SDK / imported symbols: anything starting `_Z`, `nn::`, `sead::`,
#     `gmd::`, or `__` (those live in sdk.sym / gmd / sead / main.sym
#     already; re-emitting them would duplicate the import side).
#   - addresses outside the main NSO range.
#
# Run from Ghidra Script Manager (see scripts/ghidra/README.md): paste,
# Run; output is WRITTEN TO DISK (not just the console) — the console
# prints a summary + the paths.  Idempotent: overwrites both files.
#
# Alternative headless driver: a Ghidra MCP bridge is configured for
# this project (memory [[reference_ghidra_mcp]]).  The same export can be
# produced out-of-GUI via mcp__ghidra-mcp-http__list_functions +
# get_struct_layout + get_plate_comment if running the GUI is
# inconvenient; this script is the in-GUI path.

# @author smbwap
# @category SMBW Archipelago
# @menupath

from __future__ import print_function

import json
import os

# Where to write.  Mirrors import_sdk_symbols.py's SYMS_ROOT.
SYMS_ROOT = r"C:\Users\maxwe\Documents\smwonder_archipelago\switch-mod\syms\100"
SYM_OUT = os.path.join(SYMS_ROOT, "re_discovered.sym")
STRUCT_OUT = os.path.join(SYMS_ROOT, "re_structs.json")

DEFAULT_MAIN_BASE = 0x7100000000

# Names that are Ghidra auto-generated (not our work).
_AUTO_PREFIXES = ("FUN_", "LAB_", "DAT_", "SUB_", "UNK_", "switchD_",
                  "caseD_", "EXT_", "OFF_")
# Prefixes that mean "already imported from a .sym file" — don't re-emit.
_IMPORTED_PREFIXES = ("_Z", "__", "nn::", "sead::", "gmd::", "al::")


def _is_ours(name):
    """True if `name` looks like a discovery we made (not auto, not imported)."""
    if not name:
        return False
    if name.startswith(_AUTO_PREFIXES):
        return False
    if name.startswith(_IMPORTED_PREFIXES):
        return False
    return True


def export_symbols(main_base):
    """Walk the symbol table; return (lines, count) of user-named code symbols."""
    from ghidra.program.model.symbol import SourceType

    sym_tbl = currentProgram.getSymbolTable()
    fn_mgr = currentProgram.getFunctionManager()
    lo = main_base
    hi = main_base + 0x10000000

    rows = []  # (offset, name, is_func)
    seen = set()

    # Functions first (the high-value discoveries).
    for fn in fn_mgr.getFunctions(True):
        name = fn.getName()
        if not _is_ours(name):
            continue
        a = fn.getEntryPoint().getOffset()
        if a < lo or a > hi:
            continue
        if a in seen:
            continue
        seen.add(a)
        rows.append((a - main_base, name, True))

    # Then any other user-defined labels (data, anchors, vtable markers).
    for sym in sym_tbl.getAllSymbols(True):
        if sym.getSource() != SourceType.USER_DEFINED:
            continue
        name = sym.getName()
        if not _is_ours(name):
            continue
        a = sym.getAddress()
        if a is None:
            continue
        off = a.getOffset()
        if off < lo or off > hi:
            continue
        if off in seen:
            continue
        seen.add(off)
        rows.append((off - main_base, name, False))

    rows.sort()
    lines = [
        "/* SMBW Archipelago — RE discoveries exported from Ghidra. */",
        "/* Generated by scripts/ghidra/export_re_annotations.py.      */",
        "/* Re-importable by import_sdk_symbols.py (same format).      */",
        "",
    ]
    # Lines must parse under import_sdk_symbols.py's rules: it splits on
    # '=' then '+' and runs int(offs, 0), stripping only a trailing ';'.
    # So NO inline comments after the value — keep each line clean. The
    # function/label distinction isn't needed for re-import (the importer
    # promotes to a function automatically when an instruction sits at the
    # address); it's recorded in re_structs.json instead if needed.
    for off, name, is_func in rows:
        lines.append("%s = __main_start + 0x%08x;" % (name, off))
    return lines, len(rows)


def export_structs():
    """Dump user-defined composite types (struct/union) + plate comments."""
    from ghidra.program.model.data import Composite, Union

    dtm = currentProgram.getDataTypeManager()
    structs = []
    for dt in dtm.getAllDataTypes():
        if not isinstance(dt, Composite):
            continue
        # Skip built-ins and imported library types; keep program-local ones.
        cat = dt.getCategoryPath().getPath()
        if cat.startswith("/Demangler") or cat.startswith("/std"):
            continue
        fields = []
        try:
            for comp in dt.getComponents():
                fields.append({
                    "offset": comp.getOffset(),
                    "name": comp.getFieldName() or "",
                    "type": comp.getDataType().getName(),
                    "size": comp.getLength(),
                    "comment": comp.getComment() or "",
                })
        except Exception:
            pass
        structs.append({
            "name": dt.getName(),
            "category": cat,
            "size": dt.getLength(),
            "kind": "union" if isinstance(dt, Union) else "struct",
            "fields": fields,
        })

    # Plate (function-header) comments — the prose layer of our analysis.
    plates = []
    fn_mgr = currentProgram.getFunctionManager()
    for fn in fn_mgr.getFunctions(True):
        c = fn.getComment()  # plate / repeatable header comment
        if not c:
            continue
        name = fn.getName()
        if name.startswith(_AUTO_PREFIXES) and not c.strip():
            continue
        plates.append({
            "name": name,
            "offset": fn.getEntryPoint().getOffset() - DEFAULT_MAIN_BASE,
            "comment": c,
        })

    return {"structs": structs, "plate_comments": plates}


def main():
    main_base = currentProgram.getImageBase().getOffset()
    if main_base != DEFAULT_MAIN_BASE:
        print("WARN: image base 0x%x != expected 0x%x; using actual." %
              (main_base, DEFAULT_MAIN_BASE))

    print("SMBW Archipelago: export_re_annotations.py")
    print("  program:   %s" % currentProgram.getName())
    print("  main base: 0x%x" % main_base)

    if not os.path.isdir(SYMS_ROOT):
        print("ERROR: SYMS_ROOT not found — edit the constant at top of script.")
        return

    sym_lines, sym_count = export_symbols(main_base)
    with open(SYM_OUT, "w") as f:
        f.write("\n".join(sym_lines) + "\n")

    struct_doc = export_structs()
    with open(STRUCT_OUT, "w") as f:
        json.dump(struct_doc, f, indent=2, sort_keys=True)

    n_structs = len(struct_doc["structs"])
    n_plates = len(struct_doc["plate_comments"])

    print("")
    print("===== summary =====")
    print("  %d user-named symbols  -> %s" % (sym_count, SYM_OUT))
    print("  %d struct/union types  -> %s" % (n_structs, STRUCT_OUT))
    print("  %d function plate comments (in the same json)" % n_plates)
    print("")
    if sym_count == 0:
        print("0 symbols exported — either you opened a fresh NSO with no")
        print("renames yet, or every name still matches FUN_/LAB_/imported.")
        print("Rename a few functions and re-run, or check _is_ours().")
    else:
        print("Commit both files.  On a fresh Ghidra load, re-run")
        print("import_sdk_symbols.py (it walks *.sym including re_discovered.sym)")
        print("to reapply every name.")


main()
