"""SMBWContext: CommonContext subclass for the SMBW Archipelago client.

Ported from the headless `bridge/ap_client.py`.  Key changes:
  - game name updated to first-class "SMBWonder" (no longer Manual_-prefixed).
  - `make_gui()` returns the Kivy `SMBWManager` subclass so Archipelago
    Launcher spawns a Kivy window with our custom SMBW tab (status on
    the left, log tail on the right).
  - All "SMBW" log lines (lan_server, processor, this module) route
    through the `SMBW` logger, which `SMBWManager` tails in the right
    half of the SMBW tab.

Inbound (AP -> Switch):
  - Badges: maintain a canonical badge mask derived from
    :attr:`items_received`.  On every ``ReceivedItems``, recompute the
    mask and push it to the Switch as a ``SetBadgesAbsolute`` (the LAN
    server also re-pushes on HelloMsg and on a ~2 s tick).
  - Royal Seeds: same idempotent absolute-overwrite pattern -- a 6-bit
    mask of which seeds AP has granted, pushed as
    ``SetRoyalSeedsAbsolute`` on every ReceivedItems + HelloMsg +
    periodic tick.  The Switch loops the 6 container-B bool hashes and
    grants/clears each per the mask, so an in-game palace clear that
    runs ahead of AP gets reverted within seconds.
  - Items neither table recognizes are logged + dropped.

Outbound (Switch -> AP):
  - The LanServer calls :meth:`SMBWContext.handle_check_emitted` for
    every CheckEmitted the processor produces.  We resolve to an AP
    location ID via :mod:`location_table` + the connected
    ``location_names`` and ``send_msgs([{"cmd": "LocationChecks", ...}])``.
"""
from __future__ import annotations

import asyncio
import logging
from typing import Any

from CommonClient import CommonContext  # type: ignore
from NetUtils import ClientStatus  # type: ignore

from . import badge_table
from . import coin_table
from . import royal_seed_table
from . import wonder_seed_table
from .commands import SMBWCommandProcessor
from .location_table import lookup_name
from .protocol import CheckEmitted, CheckKind, DeathReported, GoalCompleted
from .state import BridgeState


log = logging.getLogger("SMBW")


# Must match the new SMBWonderWorld's `game` slug (see
# apworld/smbw_archipelago/Game.py).
GAME_NAME = "Super Mario Bros Wonder"


# The single goal-location name (from apworld locations.json) whose
# completion is signalled by the M3.7 Switch-side Nerve trampoline at
# NSO+0x15b77a8 (SetFlagEnd...AfterClearedLastBoss).  Used to gate
# ``handle_goal_completed`` so the hook only marks AP done when the
# player actually picked the Bowser goal -- otherwise the Bowser kill
# is just a milestone, not victory.  The two other victory locations
# (Special: Wonder Gauntlet - Normal Exit, Special: WONDER? - Normal
# Exit) reach CLIENT_GOAL via ``handle_check_emitted`` matching the
# goal name on a normal LocationCheck.
GOAL_LOCATION_NAME_BOWSER = "PI: Bowser's Rage Stage - Royal Seed"


class SMBWContext(CommonContext):
    """CommonContext that ties the LAN server to the AP server.

    Construction is two-phase: the context is created early so the AP
    auth loop can start; the ``lan_server`` reference is wired in by
    :mod:`.main` after both objects exist.  Until then item-grant
    routing is silently dropped (no Switch is connected yet anyway).
    """

    game = GAME_NAME
    items_handling = 0b111  # all items via AP (no local progression)
    command_processor = SMBWCommandProcessor

    def __init__(
        self,
        server_address: str | None,
        password: str | None,
        state: BridgeState,
    ) -> None:
        super().__init__(server_address, password)
        self.bridge_state = state
        self.lan_server: Any = None  # wired post-construction
        self._location_name_to_id: dict[str, int] = {}
        self._item_name_to_id: dict[str, int] = {}
        self._sent_loc_ids: set[int] = set()

        # M3.8 DeathLink -- off by default; flipped on by slot_data
        # ``death_link`` truthy when the AP server delivers it on
        # Connected.  Gates both outbound (report_death sends Bounce iff
        # enabled) and inbound (on_deathlink forwards to Switch iff
        # enabled, belt-and-braces over CommonClient's tag-check).
        self.deathlink_enabled: bool = False

        # ``ten_coin_sanity`` slot_data toggle -- gates the outbound
        # TEN_COIN refund.  When OFF, the player's 10-coin blocks aren't
        # AP locations: the game gives +10 purple coins normally and the
        # bridge must NOT subtract them (no AP item is coming back to
        # net the refund out).  When ON, every 10-coin block is an AP
        # location, the +10 is purely a side-effect of the in-game
        # animation, and the refund makes AP the sole authority over
        # what the block actually awards.  Default ON to match the yaml
        # ``DefaultOnToggle`` -- if slot_data is missing the key entirely
        # (e.g. seed generated by an older apworld), we err toward the
        # documented option default.  The inbound ``"10 Coin"`` grant
        # is intentionally NOT gated: in a multiworld a peer with sanity
        # ON could ship a 10 Coin item to a slot with sanity OFF, and
        # the recipient should still receive the +10.
        self.ten_coin_sanity_enabled: bool = True

        # M3.7 goal-option respect (apworld fill_slot_data ships the
        # player's chosen goal as the resolved location name).  None
        # until ``Connected`` populates it; ``handle_goal_completed``
        # uses it to gate the Bowser-Nerve hook and
        # ``handle_check_emitted`` uses it to convert a goal-location
        # LocationCheck into a StatusUpdate(CLIENT_GOAL).  The dedup
        # flag stops the same session from sending CLIENT_GOAL twice
        # (e.g. Bowser kill firing both the M3.7 hook and the
        # PALACE_CLEAR check path).
        self.goal_location_name: str | None = None
        self._goal_status_sent: bool = False

        # M2.3 badge probe override -- when not None, ``_recompute_badge_mask``
        # returns this instead of the AP-derived mask.  Lets a developer
        # cycle through unmapped internal_ids (`/badge_probe <bit>`) to
        # discover which AP badge each bit corresponds to.  The 2 s
        # badge_sync tick keeps re-pushing the probe mask, so the badge
        # stays visible in-game until the override is cleared.
        self._badge_probe_mask: int | None = None

        # M2.3 known-invalid bits the user has confirmed (via
        # `/badge_probe_invalid`) don't correspond to any AP badge.
        # `/badge_probe_next` skips these so the user doesn't re-probe
        # dead bits.  Runtime-only -- not persisted across client
        # restarts; for permanent records add to ``badge_table._BADGES``
        # or paste the snippet from `/badge_status` somewhere durable.
        self._badge_probe_invalid: set[int] = set()

    # ---- AP lifecycle overrides ---------------------------------------

    async def server_auth(self, password_requested: bool = False) -> None:
        if password_requested and not self.password:
            log.warning(
                "AP server requested a password but none configured "
                "(set one in the connect command or pass --password)")
        await self.get_username()
        await self.send_connect()

    def on_package(self, cmd: str, args: dict) -> None:
        super().on_package(cmd, args)
        asyncio.create_task(self._handle_ap_package(cmd, args))

    async def _handle_ap_package(self, cmd: str, args: dict) -> None:
        if cmd == "Connected":
            log.info(
                "AP connected: slot=%s player=%s seed=%s",
                self.auth, self.slot, self.seed_name)
            self._rebuild_reverse_maps_from_context()
            # M3.8 -- pick up the player's per-slot DeathLink choice from
            # slot_data and toggle the connection tag.  Slot_data wins
            # over any local default; this is the only place the YAML's
            # ``death_link`` setting takes effect.  ``update_death_link``
            # mutates ``self.tags`` and sends a ConnectUpdate when
            # changed mid-session.
            slot_data = args.get("slot_data") or {}
            dl = bool(slot_data.get("death_link"))
            if dl != self.deathlink_enabled:
                log.info(
                    "DeathLink: %s (from slot_data)",
                    "ENABLED" if dl else "disabled")
            self.deathlink_enabled = dl
            try:
                await self.update_death_link(dl)
            except Exception:
                log.exception("update_death_link(%s) failed", dl)
            # Default ON to match the yaml DefaultOnToggle if the key is
            # missing entirely (older apworld at gen time).
            tcs = bool(slot_data.get("ten_coin_sanity", True))
            if tcs != self.ten_coin_sanity_enabled:
                log.info(
                    "ten_coin_sanity: %s (from slot_data)",
                    "ENABLED" if tcs else "disabled")
            self.ten_coin_sanity_enabled = tcs

            # M3.7 -- pick up the player's chosen goal location from
            # slot_data.  The apworld's fill_slot_data resolves the
            # integer ``goal`` option to its location name, which the
            # bridge then uses to gate both the Bowser-Nerve hook and
            # the per-check CLIENT_GOAL path.  An older apworld that
            # only ships the integer drops to None here and we fall
            # back to the prior unconditional behavior with a warning.
            goal_name = slot_data.get("goal_location_name")
            if isinstance(goal_name, str) and goal_name:
                if goal_name != self.goal_location_name:
                    log.info("goal location: %r (from slot_data)", goal_name)
                self.goal_location_name = goal_name
            else:
                log.warning(
                    "slot_data missing 'goal_location_name'; "
                    "goal hook will fire on Bowser regardless of "
                    "the player's chosen goal option")
                self.goal_location_name = None
            # Tell the AP server the player is in-game so item routing
            # starts flowing.  ClientStatus.CLIENT_PLAYING.
            try:
                await self.send_msgs([{
                    "cmd": "StatusUpdate",
                    "status": ClientStatus.CLIENT_PLAYING,
                }])
            except Exception:
                log.exception("StatusUpdate(CLIENT_PLAYING) failed")
            return

        if cmd == "DataPackage":
            self._rebuild_reverse_maps_from_context()
            return

        if cmd == "ReceivedItems":
            await self._handle_received_items(args)
            return

    def _rebuild_reverse_maps_from_context(self) -> None:
        """Build name->id reverse maps from CommonContext's id->name tables.
        Idempotent; called on Connected and on DataPackage."""
        try:
            loc_id_to_name = self.location_names[self.game]
            item_id_to_name = self.item_names[self.game]
        except Exception:
            log.exception("could not read location_names/item_names for %s", self.game)
            return
        self._location_name_to_id = {
            name: cid for cid, name in loc_id_to_name.items()
        }
        self._item_name_to_id = {
            name: cid for cid, name in item_id_to_name.items()
        }
        log.info(
            "reverse maps built: %d locations, %d items for %s",
            len(self._location_name_to_id),
            len(self._item_name_to_id),
            self.game,
        )

    def _recompute_badge_mask(self) -> int:
        """Walk :attr:`items_received` and compute the absolute owned-badge
        bitmask -- one bit per known badge item.  Items the badge table
        doesn't recognize contribute 0 bits (silent drop).  This is what
        the LAN server pushes to the Switch as the authoritative badge
        set on HelloMsg, on a periodic tick, and after every
        ReceivedItems.

        M2.3 probe override: if ``self._badge_probe_mask`` is not None,
        return it instead of the AP-derived mask.  Drives the
        `/badge_probe` command loop where a developer sets a single bit
        to see which badge it corresponds to in-game.
        """
        if self._badge_probe_mask is not None:
            return self._badge_probe_mask
        mask = 0
        for it in self.items_received:
            item_id = getattr(it, "item", None)
            if item_id is None and isinstance(it, dict):
                item_id = it.get("item")
            if item_id is None:
                continue
            try:
                item_name = self.item_names.lookup_in_game(int(item_id))
            except Exception:
                continue
            bit = badge_table.grant_internal_id_for_item(item_name)
            if bit is None:
                continue
            mask |= (1 << bit)
        return mask

    def set_badge_probe_mask(self, mask: int | None) -> None:
        """M2.3 probe-and-discover entry point.  Set or clear the badge
        probe override and immediately push a SetBadgesAbsolute so the
        Switch reflects the new mask without waiting for the next tick.

        Passing ``None`` restores AP-authoritative mode (the badge mask
        recomputes from items_received).  Passing 0 sends an empty mask
        (useful for confirming the override is active).
        """
        self._badge_probe_mask = mask
        lan = self.lan_server
        if lan is not None and hasattr(lan, "_push_badge_sync_now"):
            lan._push_badge_sync_now()

    def _recompute_wonder_seed_counts(self) -> list[int]:
        """Walk :attr:`items_received` and return cumulative Wonder Seed
        counts bucketed by world.  Returns a list of length
        ``wonder_seed_table.WORLD_COUNT`` (8 buckets:
        W1/W2/W3/W4/W5/W6/Petal Isles/Special).  Idempotent and
        side-effect-free; the bridge pushes the tuple as
        ``SetWonderSeedCountsMsg`` on HelloMsg, on every ReceivedItems,
        and on the periodic 2 s tick.  The Switch reads container-A
        hash ``0x9f5ead3c`` (current world index) and applies
        ``counts[bucket]`` via ``probe::pushWonderSeedOverride`` --
        making AP the sole authority over Wonder Seed gating.

        Items the table doesn't recognize contribute to nothing
        (silent drop), matching the rest of the table layer's fallback
        semantics."""
        counts = [0] * wonder_seed_table.WORLD_COUNT
        for it in self.items_received:
            item_id = getattr(it, "item", None)
            if item_id is None and isinstance(it, dict):
                item_id = it.get("item")
            if item_id is None:
                continue
            try:
                item_name = self.item_names.lookup_in_game(int(item_id))
            except Exception:
                continue
            idx = wonder_seed_table.world_index_for_item(item_name)
            if idx is None:
                continue
            counts[idx] += 1
        return counts

    def _recompute_wonder_seed_bits(self) -> tuple[int, int]:
        """Walk :attr:`items_received` and return the absolute 128-bit
        per-course Wonder Seed bitfield as a ``(bits_lo, bits_hi)``
        tuple of two u64s.  Bridge pushes this via
        :class:`SetWonderSeedsAbsoluteMsg`; Switch overwrites container-C
        hash ``0x60458608`` to match on every ReceivedItems / HelloMsg /
        periodic tick.  (2026-05-29)

        Bit derivation: 16 bits per world bucket.  World w occupies
        bits ``[w*16, w*16+15]``.  For each world with cumulative AP
        count ``N_w`` (capped at 16), set the lowest ``N_w`` bits in
        that range.  This is a DETERMINISTIC AP-derived bitfield that
        the Switch persistence-test workflow can verify against the
        saved file; bit positions are NOT semantically tied to specific
        in-game courses yet (refining the bit-to-course mapping
        requires additional RE of the FUN_71003D4110 Murmur3 course-
        name -> course-index lookup).

        Returns ``(0, 0)`` when no Wonder Seeds are owned; that is
        valid input to the Switch primitive and means "AP knows of no
        seeds -- clobber the bitfield to empty".  16 bits per bucket
        accommodates up to 16 seeds per world; vanilla SMBW worlds run
        up to ~17 seeds (W6 has ~34 across multiple branches), so a
        future refinement may either widen each bucket or remap to
        course indices proper."""
        counts = self._recompute_wonder_seed_counts()
        BITS_PER_WORLD = 16
        bits = 0
        for w, count in enumerate(counts):
            capped = min(count, BITS_PER_WORLD)
            if capped <= 0:
                continue
            bucket_mask = (1 << capped) - 1
            bits |= bucket_mask << (w * BITS_PER_WORLD)
        bits_lo = bits & ((1 << 64) - 1)
        bits_hi = (bits >> 64) & ((1 << 64) - 1)
        return (bits_lo, bits_hi)

    def _recompute_royal_seed_mask(self) -> int:
        """Walk :attr:`items_received` and return the absolute 6-bit
        Royal Seed mask -- one bit per world (bit 0 = W1, ..., bit 5 =
        W6).  Idempotent and side-effect-free.  Items the table doesn't
        recognize contribute 0 bits (silent drop), matching the badge
        path.

        The bridge pushes this as ``SetRoyalSeedsAbsoluteMsg`` on
        HelloMsg, on every ReceivedItems, and on the periodic 2 s tick.
        The Switch loops the 6 container-B bool hashes (see
        ``royal_seed_table.ROYAL_SEED_HASHES`` for the canonical
        order, mirrored Switch-side) and writes
        ``(mask >> bit) & 1`` to each -- granting AP-granted seeds and
        clearing any seed the player obtained in-game without AP."""
        mask = 0
        for it in self.items_received:
            item_id = getattr(it, "item", None)
            if item_id is None and isinstance(it, dict):
                item_id = it.get("item")
            if item_id is None:
                continue
            try:
                item_name = self.item_names.lookup_in_game(int(item_id))
            except Exception:
                continue
            bit = royal_seed_table.bit_for_item(item_name)
            if bit is None:
                continue
            mask |= (1 << bit)
        return mask

    async def _handle_received_items(self, args: dict) -> None:
        items = args.get("items", []) or []

        new_mask = self._recompute_badge_mask()
        new_seed_counts = self._recompute_wonder_seed_counts()
        new_royal_seed_mask = self._recompute_royal_seed_mask()
        new_ws_bits_lo, new_ws_bits_hi = self._recompute_wonder_seed_bits()
        if self.lan_server is not None:
            log.info(
                "ReceivedItems: badge mask now 0x%x, royal_seed mask 0x%x, "
                "wonder_seed counts=%s, wonder_seed bits=(0x%x, 0x%x)",
                new_mask, new_royal_seed_mask, new_seed_counts,
                new_ws_bits_lo, new_ws_bits_hi)
            self.lan_server.send_set_badges_absolute(new_mask)
            # Idempotent absolute-overwrite: AP is the sole authority
            # over container-B Royal Seed bools (same pattern as
            # badges).  Switch loops the 6 hashes per bit.
            self.lan_server.send_set_royal_seeds_absolute(new_royal_seed_mask)
            # Idempotent absolute-overwrite: AP is the sole authority
            # over the per-world Wonder Seed counts (same pattern as
            # badges).  Switch routes via current-world hash 0x9f5ead3c.
            self.lan_server.send_set_wonder_seed_counts(new_seed_counts)
            # 2026-05-29 -- AP-authoritative per-course Wonder Seed
            # bitfield (container-C hash 0x60458608).  Same idempotent
            # absolute-overwrite pattern -- Switch overwrites all 128
            # bits to match.
            self.lan_server.send_set_wonder_seeds_absolute(
                new_ws_bits_lo, new_ws_bits_hi)
        else:
            log.debug(
                "no lan_server bound; not forwarding badge mask 0x%x / "
                "royal_seed mask 0x%x / wonder_seed counts=%s / "
                "wonder_seed bits=(0x%x, 0x%x)",
                new_mask, new_royal_seed_mask, new_seed_counts,
                new_ws_bits_lo, new_ws_bits_hi)

        for it in items:
            item_id = it.get("item") if isinstance(it, dict) else None
            if item_id is None:
                item_id = getattr(it, "item", None)
            if item_id is None:
                log.warning("ReceivedItems entry without item id: %r", it)
                continue
            try:
                item_name = self.item_names.lookup_in_game(int(item_id))
            except Exception as e:
                log.warning("can't resolve item id %r: %s", item_id, e)
                continue
            if badge_table.is_badge_item(item_name):
                log.debug(
                    "badge item received: %r (id=%s) -- covered by "
                    "SetBadgesAbsolute push", item_name, item_id)
                # Auto-resolve the "<Badge> Obtained" location at grant
                # time.  Why: the Switch's badge bitfield serves dual
                # duty -- Mario equips from it AND the Poplin shop
                # refuses to sell any bit it sees set.  Granting via
                # AP sets the bit immediately, locking the shop and
                # making the in-game purchase that would normally
                # complete the location unreachable.
                bit = badge_table.grant_internal_id_for_item(item_name)
                if bit is not None:
                    check = CheckEmitted(
                        kind=CheckKind.BADGE_ACQUIRED,
                        stage_key=bit,
                        metadata={"source": "ap_grant"},
                    )
                    if self.bridge_state.emit_check(check):
                        await self.handle_check_emitted(check)
                continue
            if wonder_seed_table.is_wonder_seed_item(item_name):
                log.debug(
                    "wonder seed item received: %r (id=%s) -- covered by "
                    "SetWonderSeedCounts push", item_name, item_id)
                continue
            if royal_seed_table.is_royal_seed_item(item_name):
                log.debug(
                    "royal seed item received: %r (id=%s) -- covered by "
                    "SetRoyalSeedsAbsolute push", item_name, item_id)
                # Auto-resolve the matching "<World> Palace - Royal Seed"
                # location at grant time.  Why: setting the container-B
                # seed bool flips the world-map UI to "cleared", so the
                # player has no in-game reason to re-enter the palace --
                # the PALACE_CLEAR PlayReport that normally fires the
                # check never arrives.  See
                # ``docs/royal-seed-check-loss-re-plan.md`` for the RE
                # plan to find a path that fires the check naturally;
                # this is the short-term unblock that keeps the AP
                # location resolvable.
                stage_key = royal_seed_table.palace_stage_key_for_item(
                    item_name)
                if stage_key is not None:
                    check = CheckEmitted(
                        kind=CheckKind.PALACE_CLEAR,
                        stage_key=stage_key,
                        metadata={"source": "ap_grant"},
                    )
                    if self.bridge_state.emit_check(check):
                        await self.handle_check_emitted(check)
                continue
            if coin_table.is_coin_item(item_name):
                grant = coin_table.grant_for_item(item_name)
                if grant is None:
                    log.warning(
                        "coin_table inconsistency: "
                        "is_coin_item(%r)=True but no grant", item_name)
                    continue
                hash_, delta = grant
                log.info(
                    "item received: %r (id=%s) -> increment_hash_keyed "
                    "hash=0x%08x delta=%d",
                    item_name, item_id, hash_, delta)
                if self.lan_server is None:
                    log.debug("no lan_server bound; cannot forward grant")
                    continue
                self.lan_server.send_increment_hash_keyed(hash_, delta)
            else:
                log.info(
                    "received unhandled item %r (id=%s); ignoring "
                    "(no table entry)", item_name, item_id)

    # ---- DeathLink ----------------------------------------------------

    def on_deathlink(self, data: dict[str, Any]) -> None:
        """CommonContext dispatches this when an AP DeathLink Bounce
        arrives for a slot tagged ``DeathLink``.  Forward to the Switch
        as a KillMsg unless we sourced it ourselves (CommonClient already
        gates by timestamp; this is belt-and-braces).
        """
        super().on_deathlink(data)
        if not self.deathlink_enabled:
            return
        source = str(data.get("source") or "")
        if source and source == self._own_player_name():
            log.debug("on_deathlink: ignoring self-sourced bounce")
            return
        cause = str(data.get("cause") or "")
        if self.lan_server is None:
            log.info(
                "[deathlink in] source=%s cause=%s (no Switch bound; dropping)",
                source, cause)
            return
        log.info("[deathlink in] source=%s cause=%s -> Switch", source, cause)
        self.lan_server.send_kill(source=source, cause=cause)

    async def handle_death_reported(self, death: DeathReported) -> None:
        """LanServer dispatches this when the processor emits a
        DeathReported (a Switch-side DEATH_DETECTED that survived the
        discriminator).  We delegate to CommonContext's ``send_death``
        which composes the Bounce with our slot name as ``source`` and
        updates ``last_death_link`` (so an echo back doesn't re-trigger
        ``on_deathlink``)."""
        if not self.deathlink_enabled:
            log.debug(
                "handle_death_reported(seq=%d): deathlink disabled, dropping",
                death.seq)
            return
        try:
            await self.send_death("mario_died")
            log.info(
                "-> AP Bounce DeathLink seq=%d source=%s",
                death.seq, self._own_player_name() or "?")
        except Exception:
            log.exception("send_death failed for seq=%d", death.seq)

    # ---- Game-completion goal -----------------------------------------

    async def handle_goal_completed(self, goal: GoalCompleted) -> None:
        """LanServer dispatches this when the processor emits a
        GoalCompleted (Switch fired the SetFlagEnd...AfterClearedLastBoss
        Nerve at NSO+0x15b77a8 = Mario defeated final Bowser for the
        first time on this save).

        Sends a ``StatusUpdate`` with ``ClientStatus.CLIENT_GOAL`` only
        if the player's chosen goal is the Bowser one -- otherwise this
        Nerve is just a milestone and the actual goal (Wonder Gauntlet
        / WONDER?) is reached via ``handle_check_emitted`` matching the
        goal location name on a regular CheckEmitted.  Pre-slot_data
        fallback (no goal_location_name received): assume Bowser so
        legacy apworlds still goal-complete on Bowser kill.
        """
        if (self.goal_location_name is not None
                and self.goal_location_name != GOAL_LOCATION_NAME_BOWSER):
            log.info(
                "GameGoalReached Nerve fired (seq=%d) but goal is %r "
                "-- not signalling CLIENT_GOAL on Bowser kill",
                goal.seq, self.goal_location_name)
            return
        await self._send_client_goal(reason=f"GameGoalReached seq={goal.seq}")

    async def _send_client_goal(self, reason: str) -> None:
        """Send the StatusUpdate(CLIENT_GOAL) at most once per session.

        Both the M3.7 Bowser-Nerve path and the goal-location
        CheckEmitted path funnel through here; the AP server tolerates
        repeats but the bridge logs would be confusing if both fired
        for the same Bowser-goal seed.
        """
        if self._goal_status_sent:
            log.debug("CLIENT_GOAL already sent this session; "
                      "ignoring duplicate trigger (%s)", reason)
            return
        try:
            await self.send_msgs([{
                "cmd": "StatusUpdate",
                "status": ClientStatus.CLIENT_GOAL,
            }])
            self._goal_status_sent = True
            log.info("-> AP StatusUpdate(CLIENT_GOAL) (%s)", reason)
        except Exception:
            log.exception("StatusUpdate(CLIENT_GOAL) failed (%s)", reason)

    def _own_player_name(self) -> str:
        """Best-effort lookup of our own player name in the AP slot
        roster.  CommonContext populates ``player_names`` on Connected;
        before that, fall back to the configured ``auth`` slot name.
        Used for the self-ping guard in ``on_deathlink``."""
        try:
            return self.player_names[self.slot]
        except Exception:
            return self.auth or ""

    # ---- Outbound: LanServer's CheckEmitted callback ------------------

    async def handle_check_emitted(self, check: CheckEmitted) -> None:
        """Translate a CheckEmitted to an AP LocationChecks message."""
        # M2.3 probe-mode guard: each /badge_probe overwrites the
        # container-C bitfield, which the Switch's diff-on-overwrite
        # path then interprets as the player picking up the *previous*
        # probe's bit.  Suppress BADGE_ACQUIRED checks while a probe is
        # active so we don't spuriously tick off real AP locations
        # during exploration.  Clear the probe before genuine play
        # (`/badge_probe_clear`) to re-enable badge check emission.
        if (check.kind == CheckKind.BADGE_ACQUIRED
                and self._badge_probe_mask is not None):
            log.info(
                "badge probe active (mask=0x%x); suppressing AP "
                "LocationCheck for BADGE_ACQUIRED internal_id=%d",
                self._badge_probe_mask, check.stage_key)
            return
        name = lookup_name(check)
        if name is None:
            log.info(
                "no AP location name for kind=%s stage_key=%d (table needs "
                "extending)",
                check.kind.value, check.stage_key)
            return
        # M3.7 goal-option respect: if this check is the player's chosen
        # goal location, send CLIENT_GOAL.  Done before the loc_id
        # lookup because the apworld wipes the goal location's address
        # in create_regions, so the regular LocationCheck path would
        # log a spurious warning and drop the message.  CLIENT_GOAL is
        # the authoritative signal; the LocationCheck attempt below is
        # best-effort.
        if (self.goal_location_name is not None
                and name == self.goal_location_name):
            log.info(
                "goal-location check emitted (%r); signalling CLIENT_GOAL",
                name)
            await self._send_client_goal(
                reason=f"goal-location check {name!r}")
        loc_id = self._location_name_to_id.get(name)
        if loc_id is None:
            log.warning(
                "AP server has no id for location %r -- DataPackage missing "
                "or game name mismatch (we declared game=%s)",
                name, self.game)
            return
        if loc_id in self._sent_loc_ids:
            log.debug("AP location %r (id=%d) already sent; skipping",
                      name, loc_id)
            return
        self._sent_loc_ids.add(loc_id)
        # TEN_COIN refund: the game already added 10 to the player's
        # flower_coin counter when the block was hit; AP is the sole
        # authority over what each 10-coin block actually grants, so
        # we subtract 10 here.  If the inbound item happens to be a
        # "10 Coin" routed back to this slot, the inbound +10 cancels
        # this -10 for a net +10 (player sees the same UX as vanilla);
        # if AP scattered the item to another slot, the refund stands
        # and the player gets the actual item rather than free coins.
        # Paired with the dedup above so we refund at most once per
        # in-game pickup per session.
        #
        # Gated on ``ten_coin_sanity``: when OFF, 10-coin blocks aren't
        # AP locations and no inbound item is coming back to net the
        # refund out -- subtracting here would just drain the player's
        # purple coins for free.
        if (check.kind == CheckKind.TEN_COIN
                and self.ten_coin_sanity_enabled):
            grant = coin_table.grant_for_item("10 Coin")
            if grant is not None and self.lan_server is not None:
                hash_, delta = grant
                log.info(
                    "TEN_COIN check fired -> increment_hash_keyed "
                    "hash=0x%08x delta=%d (refund in-game pickup)",
                    hash_, -delta)
                self.lan_server.send_increment_hash_keyed(hash_, -delta)
        try:
            await self.send_msgs([
                {"cmd": "LocationChecks", "locations": [loc_id]},
            ])
            log.info("-> AP LocationChecks %r (id=%d)", name, loc_id)
        except Exception:
            log.exception(
                "send_msgs(LocationChecks=[%d]) failed; will not retry",
                loc_id)
            self._sent_loc_ids.discard(loc_id)

    # ---- GUI plumbing -------------------------------------------------

    def make_gui(self):
        """Hook called by CommonContext.run_gui() to discover the
        Kivy manager class.  Lazy-imported so headless / --nogui runs
        never touch Kivy."""
        from .gui import SMBWManager
        return SMBWManager
