"""(CheckKind, stage_key) -> AP location name table.

The processor emits ``CheckEmitted(kind, stage_key, ...)``; this table
turns those into the canonical AP location strings the multiworld
server expects.  Name resolution to numeric AP IDs happens via the
connected ``CommonContext.location_names_to_id`` at lookup time.

Full coverage as of 2026-05-25: 142 courses captured via a single-pass
playtest sweep (see ``docs/playtest-stage-key-sweep.md``) and processed
by ``scripts/build_location_table.py``.  Poplin shops were intentionally
skipped during the sweep since they don't emit their own ``course_in``
events -- those stay un-mapped until verified by re-entry.

Location names must match ``apworld/smbw_archipelago/data/locations.json``
character-for-character.  To regenerate, re-run the playtest sweep and
the build script.

The table is checked in (not generated from the apworld at import time)
because ``stage_key`` is an SMBW runtime value with no other source of
truth, and the bridge should run from a plain venv without Archipelago's
full custom_worlds loader.
"""

from __future__ import annotations

import logging
from typing import Final

from .badge_table import _BADGES
from .protocol import CheckEmitted, CheckKind


log = logging.getLogger("SMBW")



# ---- generated by scripts/build_location_table.py ----
# Stage-key constants (course_name -> u32 hash captured
# from PlayReport course_in events).
_STAGE_WELCOME_TO_THE_FLOWER_KINGDOM: Final[int] = 0xAF11F7FC   # W1: Welcome to the Flower Kingdom!
_STAGE_PIRANHA_PLANTS_ON_PARADE: Final[int] = 0x0DD67B0B   # W1: Piranha Plants on Parade
_STAGE_SCRAM_SKEDADDLERS: Final[int] = 0xFBD0AA97   # W1: Scram, Skedaddlers!
_STAGE_BADGE_HOUSE_IN_PIPE_ROCK_PLATEAU: Final[int] = 0xA3207D45   # W1: Badge House in Pipe-Rock Plateau
_STAGE_BULRUSH_COMING_THROUGH: Final[int] = 0xFE703FBD   # W1: Bulrush Coming Through!
_STAGE_HERE_COME_THE_HOPPOS: Final[int] = 0xFBD75CB8   # W1: Here Come the Hoppos
_STAGE_ROLLA_KOOPA_DERBY: Final[int] = 0x8875F4B4   # W1: Rolla Koopa Derby
_STAGE_PARACHUTE_CAP_I: Final[int] = 0xA8D377AB   # W1: Parachute Cap I
_STAGE_HURRY_HURRY: Final[int] = 0x2030D011   # W1: Hurry, Hurry
_STAGE_WONDER_TOKEN_TUNES: Final[int] = 0x77B85684   # W1: Wonder Token Tunes
_STAGE_POP_UP_HOPPO: Final[int] = 0x333F1388   # W1: Pop Up, Hoppo!
_STAGE_MOUNTAINEERING: Final[int] = 0x954EB962   # W1: Mountaineering!
_STAGE_SWAMP_PIPE_CRAWL: Final[int] = 0xA88519BD   # W1: Swamp Pipe Crawl
_STAGE_ANGRY_SPIKES_AND_SINKIN_PIPES: Final[int] = 0x87B77C93   # W1: Angry Spikes and Sinkin' Pipes
_STAGE_BULRUSH_EXPRESS: Final[int] = 0x6EE754E1   # W1: Bulrush Express
_STAGE_WALL_CLIMB_JUMP_I: Final[int] = 0xDADED63E   # W1: Wall-Climb Jump I
_STAGE_PIPE_ROCK_RUMBLE: Final[int] = 0x495A535A   # W1: Pipe-Rock Rumble
_STAGE_SPROINGS_IN_THE_TWILIGHT_FOREST: Final[int] = 0xE3EDD5E1   # W1: Sproings in the Twilight Forest
_STAGE_COSMIC_HOPPOS: Final[int] = 0x36E76342   # W1: Cosmic Hoppos
_STAGE_JET_RUN_I: Final[int] = 0x1922DA45   # W1: Jet Run I
_STAGE_BOUNCE_BOUNCE_BOUNCE: Final[int] = 0x84A34EF1   # Special: Bounce, Bounce, Bounce
_STAGE_PIPE_ROCK_PLATEAU_PALACE: Final[int] = 0x89927C97   # W1: Pipe-Rock Plateau Palace
_STAGE_ANGLER_POPLIN_S_HOUSE: Final[int] = 0x3D3FE9D4   # PI: Angler Poplin's House
_STAGE_LEAPING_SMACKEREL: Final[int] = 0x4E753510   # PI: Leaping Smackerel
_STAGE_DOLPHIN_KICK_I: Final[int] = 0x4B4B3D59   # PI: Dolphin Kick I
_STAGE_ROBBIRD_COVE: Final[int] = 0x3A5E3A7C   # PI: Robbird Cove
_STAGE_BLEWBIRD_ROOST: Final[int] = 0x1055717F   # PI: Blewbird Roost
_STAGE_OUTMAWAY_VALLEY: Final[int] = 0x3C950DF6   # W2: Outmaway Valley
_STAGE_POKIPEDE_PASS: Final[int] = 0xED24815C   # W2: Pokipede Pass
_STAGE_WALL_CLIMB_JUMP_II: Final[int] = 0x283CE2B9   # W2: Wall-Climb Jump II
_STAGE_PUZZLING_PARK: Final[int] = 0x25CD59CE   # W2: Puzzling Park
_STAGE_KICK_IT_OUTMAWAY: Final[int] = 0x093F62A1   # W2: Kick It, Outmaway
_STAGE_FLUFF_PUFF_PEAKS_CABIN: Final[int] = 0x5380FCA8   # W2: Fluff-Puff Peaks Cabin
_STAGE_CONDARTS_AWAY: Final[int] = 0xA6FF4B5D   # W2: Condarts Away!
_STAGE_POLE_BLOCK_PASSAGE: Final[int] = 0xC5256A5E   # W2: Pole Block Passage
_STAGE_JUMP_JUMP_JUMP: Final[int] = 0x9C6F85C5   # W2: Jump! Jump Jump!
_STAGE_FLOATING_HIGH_JUMP_I: Final[int] = 0x83774434   # W2: Floating High Jump I
_STAGE_FLUFF_PUFF_KERFUFF: Final[int] = 0x0FB8DE7F   # W2: Fluff-Puff Kerfuff
_STAGE_CLOUD_COVER: Final[int] = 0x0B2722F6   # W2: Cloud Cover
_STAGE_SPRING_FEET_I: Final[int] = 0xF421DB55   # W2: Spring Feet I
_STAGE_CLIMB_TO_THE_BEAT: Final[int] = 0x81796063   # Special: Climb to the Beat
_STAGE_UP_N_DOWN_WITH_PUFFY_LIFTS: Final[int] = 0x9AB4AE85   # W2: Up 'n' Down with Puffy Lifts
_STAGE_FLUFF_PUFF_PEAKS_FLYING_BATTLESHIP: Final[int] = 0xCAD86793   # W2: Fluff-Puff Peaks Flying Battleship
_STAGE_COUNTDOWN_TO_DROP_DOWN: Final[int] = 0xDD4715EC   # W2: Countdown to Drop Down
_STAGE_CRUISING_WITH_LINKING_LIFTS: Final[int] = 0x0D3CF91D   # W2: Cruising with Linking Lifts
_STAGE_ZIP_GO_ROUND: Final[int] = 0xDF2CCAC3   # W2: Zip-Go-Round
_STAGE_FLUFF_PUFF_PEAKS_PALACE: Final[int] = 0xB2B07454   # W2: Fluff-Puff Peaks Palace
_STAGE_DOLPHIN_KICK_II: Final[int] = 0xB8C524FB   # PI: Dolphin Kick II
_STAGE_SWIMMING: Final[int] = 0x01B2BA99   # PI: Swimming!
_STAGE_DOWNPOUR_UPROAR: Final[int] = 0xCC32B90F   # PI: Downpour Uproar
_STAGE_MASTER_POPLIN_S_HOUSE: Final[int] = 0x4A493BE1   # W3: Master Poplin's House
_STAGE_THE_HOPPYCAT_TRIAL: Final[int] = 0xA4C7E9C7   # W3: The Hoppycat Trial
_STAGE_THE_ANGLEFISH_TRIAL: Final[int] = 0xDE9EF793   # W3: The Anglefish Trial
_STAGE_AN_EMPTY_PARK: Final[int] = 0x103647C3   # W3: An Empty Park?
_STAGE_UNREACHABLE_TREASURE: Final[int] = 0xDCD9A44A   # W3: Unreachable Treasure?
_STAGE_WATERY_WONDER_TOKENS: Final[int] = 0xC21517B6   # W3: Watery Wonder Tokens
_STAGE_CROUCHING_HIGH_JUMP_I: Final[int] = 0xA56D29C2   # W3: Crouching High Jump I
_STAGE_THE_MIDWAY_TRIAL: Final[int] = 0xBA4A3B7A   # W3: The Midway Trial
_STAGE_THE_SHARP_TRIAL: Final[int] = 0xC9413E62   # W3: The Sharp Trial
_STAGE_THE_SUGARSTAR_TRIAL: Final[int] = 0x04BF20CF   # W3: The Sugarstar Trial
_STAGE_TIMER_SWITCH_CLIMB: Final[int] = 0x647768F3   # W3: Timer-Switch Climb
_STAGE_TIMER_SWITCH_DASH: Final[int] = 0x53835ED1   # W3: Timer-Switch Dash
_STAGE_THE_FINAL_TRIAL: Final[int] = 0xE7027BAE   # W3: The Final Trial
_STAGE_ROYAL_SEED_MANSION: Final[int] = 0xA5E2BB3A   # W3: Royal Seed Mansion
_STAGE_TRIPLE_THREAT_DELUGE: Final[int] = 0x26C121A7   # Special: Triple Threat Deluge
_STAGE_JEWEL_BLOCK_CAVE: Final[int] = 0x9BF97CAB   # PI: Jewel-Block Cave
_STAGE_PIRANHA_PLANT_REPRISE: Final[int] = 0xA47AF5AB   # Special: Piranha Plant Reprise
_STAGE_SUNBAKED_DESERT_HOUSE: Final[int] = 0x9D67C898   # W4: Sunbaked Desert House
_STAGE_ARMADS_ON_THE_ROLL: Final[int] = 0xD7309E22   # W4: Armads on the Roll
_STAGE_THE_DESERT_MYSTERY: Final[int] = 0xD5F68DBB   # W4: The Desert Mystery
_STAGE_ROLLING_BALL_HALL: Final[int] = 0x2C1FD82A   # W4: Rolling-Ball Hall
_STAGE_NINJI_JUMP_PARTY: Final[int] = 0x5524F03C   # W4: Ninji Jump Party
_STAGE_BLOOMPS_OF_THE_DESERT_SKIES: Final[int] = 0x76AB86E1   # W4: Bloomps of the Desert Skies
_STAGE_VALLEY_FULLA_SNOOTLES: Final[int] = 0xADA3AD3E   # W4: Valley Fulla Snootles
_STAGE_COLOR_SWITCH_DUNGEON: Final[int] = 0xBFB00C5A   # W4: Color-Switch Dungeon
_STAGE_SECRETS_OF_SHOVA_MANSION: Final[int] = 0x3567F540   # W4: Secrets of Shova Mansion
_STAGE_FLIGHT_OF_THE_BLOOMPS: Final[int] = 0xB1A08801   # W4: Flight of the Bloomps
_STAGE_PARACHUTE_CAP_II: Final[int] = 0xA677F55E   # W4: Parachute Cap II
_STAGE_CROUCHING_HIGH_JUMP_II: Final[int] = 0x8CFF55FD   # W4: Crouching High Jump II
_STAGE_INVISIBILITY_I: Final[int] = 0x715BCAE8   # W4: Invisibility I
_STAGE_SUNBAKED_SKIRMISH: Final[int] = 0x389A6B66   # W4: Sunbaked Skirmish
_STAGE_PIPE_PARK: Final[int] = 0xEFDA9369   # W4: Pipe Park
_STAGE_TREASURE_VAULT: Final[int] = 0xF9B39322   # W4: Treasure Vault
_STAGE_RAISE_THE_STAGE: Final[int] = 0x54710BE6   # W4: Raise the Stage
_STAGE_REVVER_RUN: Final[int] = 0xF6633FB9   # W4: Revver Run
_STAGE_FLOATING_WONDER_TOKENS: Final[int] = 0x9813AE4B   # W4: Floating Wonder Tokens
_STAGE_BOUNCY_TUNES: Final[int] = 0xA1C1F90F   # W4: Bouncy Tunes
_STAGE_LIGHTS_OUT: Final[int] = 0x813617AB   # W4: Lights Out
_STAGE_SUNBAKED_DESERT_PALACE: Final[int] = 0x1969941E   # W4: Sunbaked Desert Palace
_STAGE_POLE_BLOCK_ALLURE: Final[int] = 0xE1A9A17A   # Special: Pole Block Allure
_STAGE_LOYAL_POPLIN_S_HOUSE: Final[int] = 0x2A876538   # W5: Loyal Poplin's House
_STAGE_UPSHROOM_DOWNSHROOM: Final[int] = 0x54A60980   # W5: Upshroom Downshroom
_STAGE_TAILY_S_TOXIC_POND: Final[int] = 0x40CE8B8A   # W5: Taily's Toxic Pond
_STAGE_LIGHT_SWITCH_MANSION: Final[int] = 0x52A01B05   # W5: Light-Switch Mansion
_STAGE_BEWARE_OF_THE_RIFTS: Final[int] = 0x3FB2478C   # W5: Beware of the Rifts
_STAGE_TUMBLE_HOUSE: Final[int] = 0x36ED2775   # W5: Tumble House
_STAGE_TROTTIN_PIRANHA_PLANTS: Final[int] = 0x128C6CC8   # W5: Trottin' Piranha Plants
_STAGE_WUBBA_RUINS: Final[int] = 0x21B3A16E   # W5: Wubba Ruins
_STAGE_SWAYING_RUINS: Final[int] = 0x8882773F   # W5: Swaying Ruins
_STAGE_GRAPPLING_VINE_I: Final[int] = 0xC2CCC664   # W5: Grappling Vine I
_STAGE_FUNGI_FUNK: Final[int] = 0x82259180   # W5: Fungi Funk
_STAGE_POISON_RUINS: Final[int] = 0xCAAB3439   # W5: Poison Ruins
_STAGE_OPERATION_POPLIN_RESCUE: Final[int] = 0x87E6D263   # W5: Operation Poplin Rescue
_STAGE_DANGEROUS_DONUT_RIDE: Final[int] = 0xF0542010   # Special: Dangerous Donut Ride
_STAGE_OBSERVATORY_1: Final[int] = 0x3B24E83C   # W6: Observatory #1
_STAGE_WHERE_THE_RRRUMBAS_RULE: Final[int] = 0xF0817F3A   # W6: Where the Rrrumbas Rule
_STAGE_RAARGHS_IN_THE_RUINS: Final[int] = 0xC6CF3952   # W6: Raarghs in the Ruins
_STAGE_PULL_TURN_BURN: Final[int] = 0x7C498014   # W6: Pull, Turn, Burn
_STAGE_DEEP_MAGMA_BOG_FLYING_BATTLESHIP: Final[int] = 0x9D0747BD   # W6: Deep Magma Bog Flying Battleship
_STAGE_HOT_HOT_HOT: Final[int] = 0xEEBAC115   # W6: Hot-Hot Hot!
_STAGE_WAVY_RIDE_THROUGH_THE_MAGMA_TUBE: Final[int] = 0x362C12B2   # W6: Wavy Ride through the Magma Tube
_STAGE_DRAGON_BONEYARD: Final[int] = 0x4E4BF594   # W6: Dragon Boneyard
_STAGE_FLOATING_HIGH_JUMP_II: Final[int] = 0xB824B96F   # W6: Floating High Jump II
_STAGE_BOOSTING_SPIN_JUMP_II: Final[int] = 0xC8047777   # W6: Boosting Spin Jump II
_STAGE_GRAPPLING_VINE_II: Final[int] = 0x51FC5E9E   # W6: Grappling Vine II
_STAGE_MAGMA_FLARE_UP: Final[int] = 0x086183F8   # W6: Magma Flare-Up
_STAGE_ITEM_PARK: Final[int] = 0x333AB7F4   # W6: Item Park
_STAGE_HOT_HOT_ROCKS: Final[int] = 0x67BE7C0E   # W6: Hot-Hot Rocks
_STAGE_OBSERVATORY_2: Final[int] = 0x3217F3D0   # W6: Observatory #2
_STAGE_OBSERVATORY_3: Final[int] = 0x46D083C8   # W6: Observatory #3
_STAGE_OBSERVATORY_4: Final[int] = 0x86D3E8CB   # W6: Observatory #4
_STAGE_DEEP_MAGMA_BOG_PALACE: Final[int] = 0x7E523816   # W6: Deep Magma Bog Palace
_STAGE_JET_RUN_II: Final[int] = 0x69B9F9E6   # W6: Jet Run II
_STAGE_INVISIBILITY_II: Final[int] = 0xF065407A   # W6: Invisibility II
_STAGE_SPRING_FEET_II: Final[int] = 0xAE4E8917   # W6: Spring Feet II
_STAGE_SOLAR_ROLLER: Final[int] = 0x8D049038   # Special: Solar Roller
_STAGE_PETAL_ISLES_FLYING_BATTLESHIP: Final[int] = 0x2F678DCD   # PI: Petal Isles Flying Battleship
_STAGE_GNAWSHER_LAIR: Final[int] = 0x5E126A16   # PI: Gnawsher Lair
_STAGE_MAW_MAW_MOUTHFUL: Final[int] = 0x4AC313BF   # PI: Maw-Maw Mouthful
_STAGE_BOOSTING_SPIN_JUMP_I: Final[int] = 0xABE6B13D   # PI: Boosting Spin Jump I
_STAGE_SPELUNKING: Final[int] = 0x13F9E775   # PI: Spelunking!
_STAGE_PETAL_MEDDLE: Final[int] = 0x28382D44   # PI: Petal Meddle
_STAGE_WAY_OF_THE_GOOMBA: Final[int] = 0xDFE44219   # Special: Way of the Goomba
_STAGE_MUNCHER_FIELDS: Final[int] = 0x19B2169C   # PI: Muncher Fields
_STAGE_MISSILE_MEG_MAYHEM: Final[int] = 0x4866EB2F   # PI: Missile Meg Mayhem
_STAGE_HIGH_VOLTAGE_GAUNTLET: Final[int] = 0x6C3B527E   # PI: High-Voltage Gauntlet
_STAGE_EVADE_THE_SEEKER_BULLET_BILLS: Final[int] = 0x7A214398   # PI: Evade the Seeker Bullet Bills!
_STAGE_KNUCKLEFEST_BOWSER_S_BLAZING_BEATS: Final[int] = 0x33A5034F   # PI: KnuckleFest Bowser's Blazing Beats
_STAGE_BOWSER_S_RAGE_STAGE: Final[int] = 0x6895BF00   # PI: Bowser's Rage Stage
_STAGE_WONDER_GAUNTLET: Final[int] = 0x4871EB85   # Special: Wonder Gauntlet
_STAGE_BADGE_MARATHON: Final[int] = 0x3029665D   # Special: Badge Marathon
_STAGE_WONDER: Final[int] = 0x2D438F37   # Special: WONDER?

# (CheckKind, stage_key) -> AP location name.
#
# Note: for CheckKind.BADGE_ACQUIRED, ``stage_key`` holds the badge bit
# position (== SMBW internal_id), not a course key.  See
# ``protocol.CheckEmitted.stage_key`` docstring for the per-kind
# semantics.  Badge entries are appended below from ``badge_table._BADGES``
# so adding a new internal_id mapping in one place flows through to
# both the inbound grant path and the outbound check path.
_TABLE: Final[dict[tuple[CheckKind, int], str]] = {
    (CheckKind.NORMAL_EXIT, _STAGE_WELCOME_TO_THE_FLOWER_KINGDOM): "W1: Welcome to the Flower Kingdom! - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_WELCOME_TO_THE_FLOWER_KINGDOM): "W1: Welcome to the Flower Kingdom! - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_WELCOME_TO_THE_FLOWER_KINGDOM): "W1: Welcome to the Flower Kingdom! - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_PIRANHA_PLANTS_ON_PARADE): "W1: Piranha Plants on Parade - Normal Exit",
    (CheckKind.SECRET_EXIT, _STAGE_PIRANHA_PLANTS_ON_PARADE): "W1: Piranha Plants on Parade - Secret Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_PIRANHA_PLANTS_ON_PARADE): "W1: Piranha Plants on Parade - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_PIRANHA_PLANTS_ON_PARADE): "W1: Piranha Plants on Parade - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_SCRAM_SKEDADDLERS): "W1: Scram, Skedaddlers! - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_SCRAM_SKEDADDLERS): "W1: Scram, Skedaddlers! - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_SCRAM_SKEDADDLERS): "W1: Scram, Skedaddlers! - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_BADGE_HOUSE_IN_PIPE_ROCK_PLATEAU): "W1: Badge House in Pipe-Rock Plateau - Normal Exit",
    (CheckKind.NORMAL_EXIT, _STAGE_BULRUSH_COMING_THROUGH): "W1: Bulrush Coming Through! - Normal Exit",
    (CheckKind.SECRET_EXIT, _STAGE_BULRUSH_COMING_THROUGH): "W1: Bulrush Coming Through! - Secret Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_BULRUSH_COMING_THROUGH): "W1: Bulrush Coming Through! - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_BULRUSH_COMING_THROUGH): "W1: Bulrush Coming Through! - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_HERE_COME_THE_HOPPOS): "W1: Here Come the Hoppos - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_HERE_COME_THE_HOPPOS): "W1: Here Come the Hoppos - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_HERE_COME_THE_HOPPOS): "W1: Here Come the Hoppos - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_ROLLA_KOOPA_DERBY): "W1: Rolla Koopa Derby - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_ROLLA_KOOPA_DERBY): "W1: Rolla Koopa Derby - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_ROLLA_KOOPA_DERBY): "W1: Rolla Koopa Derby - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_PARACHUTE_CAP_I): "W1: Parachute Cap I - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_PARACHUTE_CAP_I): "W1: Parachute Cap I - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_HURRY_HURRY): "W1: Hurry, Hurry - Wonder Seed",
    (CheckKind.WONDER_SEED, _STAGE_WONDER_TOKEN_TUNES): "W1: Wonder Token Tunes - Wonder Seed",
    (CheckKind.WONDER_SEED, _STAGE_POP_UP_HOPPO): "W1: Pop Up, Hoppo! - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_MOUNTAINEERING): "W1: Mountaineering! - Normal Exit",
    (CheckKind.NORMAL_EXIT, _STAGE_SWAMP_PIPE_CRAWL): "W1: Swamp Pipe Crawl - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_SWAMP_PIPE_CRAWL): "W1: Swamp Pipe Crawl - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_SWAMP_PIPE_CRAWL): "W1: Swamp Pipe Crawl - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_ANGRY_SPIKES_AND_SINKIN_PIPES): "W1: Angry Spikes and Sinkin' Pipes - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_ANGRY_SPIKES_AND_SINKIN_PIPES): "W1: Angry Spikes and Sinkin' Pipes - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_ANGRY_SPIKES_AND_SINKIN_PIPES): "W1: Angry Spikes and Sinkin' Pipes - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_BULRUSH_EXPRESS): "W1: Bulrush Express - Normal Exit",
    (CheckKind.SECRET_EXIT, _STAGE_BULRUSH_EXPRESS): "W1: Bulrush Express - Secret Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_BULRUSH_EXPRESS): "W1: Bulrush Express - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_BULRUSH_EXPRESS): "W1: Bulrush Express - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_WALL_CLIMB_JUMP_I): "W1: Wall-Climb Jump I - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_WALL_CLIMB_JUMP_I): "W1: Wall-Climb Jump I - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_PIPE_ROCK_RUMBLE): "W1: Pipe-Rock Rumble - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_SPROINGS_IN_THE_TWILIGHT_FOREST): "W1: Sproings in the Twilight Forest - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_SPROINGS_IN_THE_TWILIGHT_FOREST): "W1: Sproings in the Twilight Forest - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_SPROINGS_IN_THE_TWILIGHT_FOREST): "W1: Sproings in the Twilight Forest - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_COSMIC_HOPPOS): "W1: Cosmic Hoppos - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_COSMIC_HOPPOS): "W1: Cosmic Hoppos - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_COSMIC_HOPPOS): "W1: Cosmic Hoppos - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_JET_RUN_I): "W1: Jet Run I - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_JET_RUN_I): "W1: Jet Run I - Top of Flag",
    (CheckKind.NORMAL_EXIT, _STAGE_BOUNCE_BOUNCE_BOUNCE): "Special: Bounce, Bounce, Bounce - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_BOUNCE_BOUNCE_BOUNCE): "Special: Bounce, Bounce, Bounce - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_BOUNCE_BOUNCE_BOUNCE): "Special: Bounce, Bounce, Bounce - Wonder Seed",
    (CheckKind.PALACE_CLEAR, _STAGE_PIPE_ROCK_PLATEAU_PALACE): "W1: Pipe-Rock Plateau Palace - Royal Seed",
    (CheckKind.WONDER_SEED, _STAGE_PIPE_ROCK_PLATEAU_PALACE): "W1: Pipe-Rock Plateau Palace - Wonder Seed",
    (CheckKind.WONDER_SEED, _STAGE_ANGLER_POPLIN_S_HOUSE): "PI: Angler Poplin's House - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_LEAPING_SMACKEREL): "PI: Leaping Smackerel - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_LEAPING_SMACKEREL): "PI: Leaping Smackerel - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_LEAPING_SMACKEREL): "PI: Leaping Smackerel - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_DOLPHIN_KICK_I): "PI: Dolphin Kick I - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_DOLPHIN_KICK_I): "PI: Dolphin Kick I - Top of Flag",
    (CheckKind.NORMAL_EXIT, _STAGE_ROBBIRD_COVE): "PI: Robbird Cove - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_ROBBIRD_COVE): "PI: Robbird Cove - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_ROBBIRD_COVE): "PI: Robbird Cove - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_BLEWBIRD_ROOST): "PI: Blewbird Roost - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_BLEWBIRD_ROOST): "PI: Blewbird Roost - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_BLEWBIRD_ROOST): "PI: Blewbird Roost - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_OUTMAWAY_VALLEY): "W2: Outmaway Valley - Normal Exit",
    (CheckKind.SECRET_EXIT, _STAGE_OUTMAWAY_VALLEY): "W2: Outmaway Valley - Secret Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_OUTMAWAY_VALLEY): "W2: Outmaway Valley - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_OUTMAWAY_VALLEY): "W2: Outmaway Valley - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_POKIPEDE_PASS): "W2: Pokipede Pass - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_POKIPEDE_PASS): "W2: Pokipede Pass - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_POKIPEDE_PASS): "W2: Pokipede Pass - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_WALL_CLIMB_JUMP_II): "W2: Wall-Climb Jump II - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_WALL_CLIMB_JUMP_II): "W2: Wall-Climb Jump II - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_PUZZLING_PARK): "W2: Puzzling Park - Wonder Seed",
    (CheckKind.WONDER_SEED, _STAGE_KICK_IT_OUTMAWAY): "W2: Kick It, Outmaway - Wonder Seed",
    (CheckKind.WONDER_SEED, _STAGE_FLUFF_PUFF_PEAKS_CABIN): "W2: Fluff-Puff Peaks Cabin - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_CONDARTS_AWAY): "W2: Condarts Away! - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_CONDARTS_AWAY): "W2: Condarts Away! - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_CONDARTS_AWAY): "W2: Condarts Away! - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_POLE_BLOCK_PASSAGE): "W2: Pole Block Passage - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_POLE_BLOCK_PASSAGE): "W2: Pole Block Passage - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_POLE_BLOCK_PASSAGE): "W2: Pole Block Passage - Wonder Seed",
    (CheckKind.FAKE_EXIT, _STAGE_JUMP_JUMP_JUMP): "W2: Jump! Jump Jump! - Fake Exit",
    (CheckKind.NORMAL_EXIT, _STAGE_JUMP_JUMP_JUMP): "W2: Jump! Jump Jump! - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_JUMP_JUMP_JUMP): "W2: Jump! Jump Jump! - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_JUMP_JUMP_JUMP): "W2: Jump! Jump Jump! - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_FLOATING_HIGH_JUMP_I): "W2: Floating High Jump I - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_FLOATING_HIGH_JUMP_I): "W2: Floating High Jump I - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_FLUFF_PUFF_KERFUFF): "W2: Fluff-Puff Kerfuff - Wonder Seed",
    (CheckKind.WONDER_SEED, _STAGE_CLOUD_COVER): "W2: Cloud Cover - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_SPRING_FEET_I): "W2: Spring Feet I - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_SPRING_FEET_I): "W2: Spring Feet I - Top of Flag",
    (CheckKind.NORMAL_EXIT, _STAGE_CLIMB_TO_THE_BEAT): "Special: Climb to the Beat - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_CLIMB_TO_THE_BEAT): "Special: Climb to the Beat - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_CLIMB_TO_THE_BEAT): "Special: Climb to the Beat - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_UP_N_DOWN_WITH_PUFFY_LIFTS): "W2: Up 'n' Down with Puffy Lifts - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_UP_N_DOWN_WITH_PUFFY_LIFTS): "W2: Up 'n' Down with Puffy Lifts - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_UP_N_DOWN_WITH_PUFFY_LIFTS): "W2: Up 'n' Down with Puffy Lifts - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_FLUFF_PUFF_PEAKS_FLYING_BATTLESHIP): "W2: Fluff-Puff Peaks Flying Battleship - Normal Exit",
    (CheckKind.WONDER_SEED, _STAGE_FLUFF_PUFF_PEAKS_FLYING_BATTLESHIP): "W2: Fluff-Puff Peaks Flying Battleship - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_COUNTDOWN_TO_DROP_DOWN): "W2: Countdown to Drop Down - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_COUNTDOWN_TO_DROP_DOWN): "W2: Countdown to Drop Down - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_COUNTDOWN_TO_DROP_DOWN): "W2: Countdown to Drop Down - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_CRUISING_WITH_LINKING_LIFTS): "W2: Cruising with Linking Lifts - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_CRUISING_WITH_LINKING_LIFTS): "W2: Cruising with Linking Lifts - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_CRUISING_WITH_LINKING_LIFTS): "W2: Cruising with Linking Lifts - Wonder Seed",
    (CheckKind.WONDER_SEED, _STAGE_ZIP_GO_ROUND): "W2: Zip-Go-Round - Wonder Seed",
    (CheckKind.PALACE_CLEAR, _STAGE_FLUFF_PUFF_PEAKS_PALACE): "W2: Fluff-Puff Peaks Palace - Royal Seed",
    (CheckKind.WONDER_SEED, _STAGE_FLUFF_PUFF_PEAKS_PALACE): "W2: Fluff-Puff Peaks Palace - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_DOLPHIN_KICK_II): "PI: Dolphin Kick II - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_DOLPHIN_KICK_II): "PI: Dolphin Kick II - Top of Flag",
    (CheckKind.NORMAL_EXIT, _STAGE_SWIMMING): "PI: Swimming! - Normal Exit",
    (CheckKind.NORMAL_EXIT, _STAGE_DOWNPOUR_UPROAR): "PI: Downpour Uproar - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_DOWNPOUR_UPROAR): "PI: Downpour Uproar - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_DOWNPOUR_UPROAR): "PI: Downpour Uproar - Wonder Seed",
    (CheckKind.WONDER_SEED, _STAGE_MASTER_POPLIN_S_HOUSE): "W3: Master Poplin's House - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_THE_HOPPYCAT_TRIAL): "W3: The Hoppycat Trial - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_THE_HOPPYCAT_TRIAL): "W3: The Hoppycat Trial - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_THE_HOPPYCAT_TRIAL): "W3: The Hoppycat Trial - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_THE_ANGLEFISH_TRIAL): "W3: The Anglefish Trial - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_THE_ANGLEFISH_TRIAL): "W3: The Anglefish Trial - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_THE_ANGLEFISH_TRIAL): "W3: The Anglefish Trial - Wonder Seed",
    (CheckKind.WONDER_SEED, _STAGE_AN_EMPTY_PARK): "W3: An Empty Park? - Wonder Seed",
    (CheckKind.WONDER_SEED, _STAGE_UNREACHABLE_TREASURE): "W3: Unreachable Treasure? - Wonder Seed",
    (CheckKind.WONDER_SEED, _STAGE_WATERY_WONDER_TOKENS): "W3: Watery Wonder Tokens - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_CROUCHING_HIGH_JUMP_I): "W3: Crouching High Jump I - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_CROUCHING_HIGH_JUMP_I): "W3: Crouching High Jump I - Top of Flag",
    (CheckKind.NORMAL_EXIT, _STAGE_THE_MIDWAY_TRIAL): "W3: The Midway Trial - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_THE_MIDWAY_TRIAL): "W3: The Midway Trial - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_THE_MIDWAY_TRIAL): "W3: The Midway Trial - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_THE_SHARP_TRIAL): "W3: The Sharp Trial - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_THE_SHARP_TRIAL): "W3: The Sharp Trial - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_THE_SHARP_TRIAL): "W3: The Sharp Trial - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_THE_SUGARSTAR_TRIAL): "W3: The Sugarstar Trial - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_THE_SUGARSTAR_TRIAL): "W3: The Sugarstar Trial - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_THE_SUGARSTAR_TRIAL): "W3: The Sugarstar Trial - Wonder Seed",
    (CheckKind.WONDER_SEED, _STAGE_TIMER_SWITCH_CLIMB): "W3: Timer-Switch Climb - Wonder Seed",
    (CheckKind.WONDER_SEED, _STAGE_TIMER_SWITCH_DASH): "W3: Timer-Switch Dash - Wonder Seed",
    (CheckKind.FAKE_EXIT, _STAGE_THE_FINAL_TRIAL): "W3: The Final Trial - Fake Exit",
    (CheckKind.NORMAL_EXIT, _STAGE_THE_FINAL_TRIAL): "W3: The Final Trial - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_THE_FINAL_TRIAL): "W3: The Final Trial - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_THE_FINAL_TRIAL): "W3: The Final Trial - Wonder Seed",
    (CheckKind.PALACE_CLEAR, _STAGE_ROYAL_SEED_MANSION): "W3: Royal Seed Mansion - Royal Seed",
    (CheckKind.SECRET_EXIT, _STAGE_ROYAL_SEED_MANSION): "W3: Royal Seed Mansion - Secret Exit",
    (CheckKind.NORMAL_EXIT, _STAGE_TRIPLE_THREAT_DELUGE): "Special: Triple Threat Deluge - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_TRIPLE_THREAT_DELUGE): "Special: Triple Threat Deluge - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_TRIPLE_THREAT_DELUGE): "Special: Triple Threat Deluge - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_JEWEL_BLOCK_CAVE): "PI: Jewel-Block Cave - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_JEWEL_BLOCK_CAVE): "PI: Jewel-Block Cave - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_JEWEL_BLOCK_CAVE): "PI: Jewel-Block Cave - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_PIRANHA_PLANT_REPRISE): "Special: Piranha Plant Reprise - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_PIRANHA_PLANT_REPRISE): "Special: Piranha Plant Reprise - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_PIRANHA_PLANT_REPRISE): "Special: Piranha Plant Reprise - Wonder Seed",
    (CheckKind.WONDER_SEED, _STAGE_SUNBAKED_DESERT_HOUSE): "W4: Sunbaked Desert House - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_ARMADS_ON_THE_ROLL): "W4: Armads on the Roll - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_ARMADS_ON_THE_ROLL): "W4: Armads on the Roll - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_ARMADS_ON_THE_ROLL): "W4: Armads on the Roll - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_THE_DESERT_MYSTERY): "W4: The Desert Mystery - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_THE_DESERT_MYSTERY): "W4: The Desert Mystery - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_THE_DESERT_MYSTERY): "W4: The Desert Mystery - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_ROLLING_BALL_HALL): "W4: Rolling-Ball Hall - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_ROLLING_BALL_HALL): "W4: Rolling-Ball Hall - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_ROLLING_BALL_HALL): "W4: Rolling-Ball Hall - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_NINJI_JUMP_PARTY): "W4: Ninji Jump Party - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_NINJI_JUMP_PARTY): "W4: Ninji Jump Party - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_NINJI_JUMP_PARTY): "W4: Ninji Jump Party - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_BLOOMPS_OF_THE_DESERT_SKIES): "W4: Bloomps of the Desert Skies - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_BLOOMPS_OF_THE_DESERT_SKIES): "W4: Bloomps of the Desert Skies - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_BLOOMPS_OF_THE_DESERT_SKIES): "W4: Bloomps of the Desert Skies - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_VALLEY_FULLA_SNOOTLES): "W4: Valley Fulla Snootles - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_VALLEY_FULLA_SNOOTLES): "W4: Valley Fulla Snootles - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_VALLEY_FULLA_SNOOTLES): "W4: Valley Fulla Snootles - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_COLOR_SWITCH_DUNGEON): "W4: Color-Switch Dungeon - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_COLOR_SWITCH_DUNGEON): "W4: Color-Switch Dungeon - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_COLOR_SWITCH_DUNGEON): "W4: Color-Switch Dungeon - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_SECRETS_OF_SHOVA_MANSION): "W4: Secrets of Shova Mansion - Normal Exit",
    (CheckKind.SECRET_EXIT, _STAGE_SECRETS_OF_SHOVA_MANSION): "W4: Secrets of Shova Mansion - Secret Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_SECRETS_OF_SHOVA_MANSION): "W4: Secrets of Shova Mansion - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_SECRETS_OF_SHOVA_MANSION): "W4: Secrets of Shova Mansion - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_FLIGHT_OF_THE_BLOOMPS): "W4: Flight of the Bloomps - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_FLIGHT_OF_THE_BLOOMPS): "W4: Flight of the Bloomps - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_FLIGHT_OF_THE_BLOOMPS): "W4: Flight of the Bloomps - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_PARACHUTE_CAP_II): "W4: Parachute Cap II - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_PARACHUTE_CAP_II): "W4: Parachute Cap II - Top of Flag",
    (CheckKind.NORMAL_EXIT, _STAGE_CROUCHING_HIGH_JUMP_II): "W4: Crouching High Jump II - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_CROUCHING_HIGH_JUMP_II): "W4: Crouching High Jump II - Top of Flag",
    (CheckKind.NORMAL_EXIT, _STAGE_INVISIBILITY_I): "W4: Invisibility I - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_INVISIBILITY_I): "W4: Invisibility I - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_SUNBAKED_SKIRMISH): "W4: Sunbaked Skirmish - Wonder Seed",
    (CheckKind.WONDER_SEED, _STAGE_PIPE_PARK): "W4: Pipe Park - Wonder Seed",
    (CheckKind.WONDER_SEED, _STAGE_TREASURE_VAULT): "W4: Treasure Vault - Wonder Seed",
    (CheckKind.WONDER_SEED, _STAGE_RAISE_THE_STAGE): "W4: Raise the Stage - Wonder Seed",
    (CheckKind.WONDER_SEED, _STAGE_REVVER_RUN): "W4: Revver Run - Wonder Seed",
    (CheckKind.WONDER_SEED, _STAGE_FLOATING_WONDER_TOKENS): "W4: Floating Wonder Tokens - Wonder Seed",
    (CheckKind.WONDER_SEED, _STAGE_BOUNCY_TUNES): "W4: Bouncy Tunes - Wonder Seed",
    (CheckKind.WONDER_SEED, _STAGE_LIGHTS_OUT): "W4: Lights Out - Wonder Seed",
    (CheckKind.PALACE_CLEAR, _STAGE_SUNBAKED_DESERT_PALACE): "W4: Sunbaked Desert Palace - Royal Seed",
    (CheckKind.WONDER_SEED, _STAGE_SUNBAKED_DESERT_PALACE): "W4: Sunbaked Desert Palace - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_POLE_BLOCK_ALLURE): "Special: Pole Block Allure - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_POLE_BLOCK_ALLURE): "Special: Pole Block Allure - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_POLE_BLOCK_ALLURE): "Special: Pole Block Allure - Wonder Seed",
    (CheckKind.WONDER_SEED, _STAGE_LOYAL_POPLIN_S_HOUSE): "W5: Loyal Poplin's House - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_UPSHROOM_DOWNSHROOM): "W5: Upshroom Downshroom - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_UPSHROOM_DOWNSHROOM): "W5: Upshroom Downshroom - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_UPSHROOM_DOWNSHROOM): "W5: Upshroom Downshroom - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_TAILY_S_TOXIC_POND): "W5: Taily's Toxic Pond - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_TAILY_S_TOXIC_POND): "W5: Taily's Toxic Pond - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_TAILY_S_TOXIC_POND): "W5: Taily's Toxic Pond - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_LIGHT_SWITCH_MANSION): "W5: Light-Switch Mansion - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_LIGHT_SWITCH_MANSION): "W5: Light-Switch Mansion - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_LIGHT_SWITCH_MANSION): "W5: Light-Switch Mansion - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_BEWARE_OF_THE_RIFTS): "W5: Beware of the Rifts - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_BEWARE_OF_THE_RIFTS): "W5: Beware of the Rifts - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_BEWARE_OF_THE_RIFTS): "W5: Beware of the Rifts - Wonder Seed",
    (CheckKind.WONDER_SEED, _STAGE_TUMBLE_HOUSE): "W5: Tumble House - Wonder Seed",
    (CheckKind.WONDER_SEED, _STAGE_TROTTIN_PIRANHA_PLANTS): "W5: Trottin' Piranha Plants - Wonder Seed",
    (CheckKind.FAKE_EXIT, _STAGE_WUBBA_RUINS): "W5: Wubba Ruins - Fake Exit",
    (CheckKind.NORMAL_EXIT, _STAGE_WUBBA_RUINS): "W5: Wubba Ruins - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_WUBBA_RUINS): "W5: Wubba Ruins - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_WUBBA_RUINS): "W5: Wubba Ruins - Wonder Seed",
    (CheckKind.FAKE_EXIT, _STAGE_SWAYING_RUINS): "W5: Swaying Ruins - Fake Exit",
    (CheckKind.NORMAL_EXIT, _STAGE_SWAYING_RUINS): "W5: Swaying Ruins - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_SWAYING_RUINS): "W5: Swaying Ruins - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_SWAYING_RUINS): "W5: Swaying Ruins - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_GRAPPLING_VINE_I): "W5: Grappling Vine I - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_GRAPPLING_VINE_I): "W5: Grappling Vine I - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_FUNGI_FUNK): "W5: Fungi Funk - Wonder Seed",
    (CheckKind.FAKE_EXIT, _STAGE_POISON_RUINS): "W5: Poison Ruins - Fake Exit",
    (CheckKind.NORMAL_EXIT, _STAGE_POISON_RUINS): "W5: Poison Ruins - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_POISON_RUINS): "W5: Poison Ruins - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_POISON_RUINS): "W5: Poison Ruins - Wonder Seed",
    (CheckKind.PALACE_CLEAR, _STAGE_OPERATION_POPLIN_RESCUE): "W5: Operation Poplin Rescue - Royal Seed",
    (CheckKind.SECRET_EXIT, _STAGE_OPERATION_POPLIN_RESCUE): "W5: Operation Poplin Rescue - Secret Exit",
    (CheckKind.WONDER_SEED, _STAGE_OPERATION_POPLIN_RESCUE): "W5: Operation Poplin Rescue - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_DANGEROUS_DONUT_RIDE): "Special: Dangerous Donut Ride - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_DANGEROUS_DONUT_RIDE): "Special: Dangerous Donut Ride - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_DANGEROUS_DONUT_RIDE): "Special: Dangerous Donut Ride - Wonder Seed",
    (CheckKind.WONDER_SEED, _STAGE_OBSERVATORY_1): "W6: Observatory #1 - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_WHERE_THE_RRRUMBAS_RULE): "W6: Where the Rrrumbas Rule - Normal Exit",
    (CheckKind.SECRET_EXIT, _STAGE_WHERE_THE_RRRUMBAS_RULE): "W6: Where the Rrrumbas Rule - Secret Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_WHERE_THE_RRRUMBAS_RULE): "W6: Where the Rrrumbas Rule - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_WHERE_THE_RRRUMBAS_RULE): "W6: Where the Rrrumbas Rule - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_RAARGHS_IN_THE_RUINS): "W6: Raarghs in the Ruins - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_RAARGHS_IN_THE_RUINS): "W6: Raarghs in the Ruins - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_RAARGHS_IN_THE_RUINS): "W6: Raarghs in the Ruins - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_PULL_TURN_BURN): "W6: Pull, Turn, Burn - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_PULL_TURN_BURN): "W6: Pull, Turn, Burn - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_PULL_TURN_BURN): "W6: Pull, Turn, Burn - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_DEEP_MAGMA_BOG_FLYING_BATTLESHIP): "W6: Deep Magma Bog Flying Battleship - Normal Exit",
    (CheckKind.WONDER_SEED, _STAGE_DEEP_MAGMA_BOG_FLYING_BATTLESHIP): "W6: Deep Magma Bog Flying Battleship - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_HOT_HOT_HOT): "W6: Hot-Hot Hot! - Normal Exit",
    (CheckKind.SECRET_EXIT, _STAGE_HOT_HOT_HOT): "W6: Hot-Hot Hot! - Secret Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_HOT_HOT_HOT): "W6: Hot-Hot Hot! - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_HOT_HOT_HOT): "W6: Hot-Hot Hot! - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_WAVY_RIDE_THROUGH_THE_MAGMA_TUBE): "W6: Wavy Ride through the Magma Tube - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_WAVY_RIDE_THROUGH_THE_MAGMA_TUBE): "W6: Wavy Ride through the Magma Tube - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_WAVY_RIDE_THROUGH_THE_MAGMA_TUBE): "W6: Wavy Ride through the Magma Tube - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_DRAGON_BONEYARD): "W6: Dragon Boneyard - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_DRAGON_BONEYARD): "W6: Dragon Boneyard - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_DRAGON_BONEYARD): "W6: Dragon Boneyard - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_FLOATING_HIGH_JUMP_II): "W6: Floating High Jump II - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_FLOATING_HIGH_JUMP_II): "W6: Floating High Jump II - Top of Flag",
    (CheckKind.NORMAL_EXIT, _STAGE_BOOSTING_SPIN_JUMP_II): "W6: Boosting Spin Jump II - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_BOOSTING_SPIN_JUMP_II): "W6: Boosting Spin Jump II - Top of Flag",
    (CheckKind.NORMAL_EXIT, _STAGE_GRAPPLING_VINE_II): "W6: Grappling Vine II - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_GRAPPLING_VINE_II): "W6: Grappling Vine II - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_MAGMA_FLARE_UP): "W6: Magma Flare-Up - Wonder Seed",
    (CheckKind.WONDER_SEED, _STAGE_ITEM_PARK): "W6: Item Park - Wonder Seed",
    (CheckKind.WONDER_SEED, _STAGE_HOT_HOT_ROCKS): "W6: Hot-Hot Rocks - Wonder Seed",
    (CheckKind.WONDER_SEED, _STAGE_OBSERVATORY_2): "W6: Observatory #2 - Wonder Seed",
    (CheckKind.WONDER_SEED, _STAGE_OBSERVATORY_3): "W6: Observatory #3 - Wonder Seed",
    (CheckKind.WONDER_SEED, _STAGE_OBSERVATORY_4): "W6: Observatory #4 - Wonder Seed",
    (CheckKind.PALACE_CLEAR, _STAGE_DEEP_MAGMA_BOG_PALACE): "W6: Deep Magma Bog Palace - Royal Seed",
    (CheckKind.WONDER_SEED, _STAGE_DEEP_MAGMA_BOG_PALACE): "W6: Deep Magma Bog Palace - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_JET_RUN_II): "W6: Jet Run II - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_JET_RUN_II): "W6: Jet Run II - Top of Flag",
    (CheckKind.NORMAL_EXIT, _STAGE_INVISIBILITY_II): "W6: Invisibility II - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_INVISIBILITY_II): "W6: Invisibility II - Top of Flag",
    (CheckKind.NORMAL_EXIT, _STAGE_SPRING_FEET_II): "W6: Spring Feet II - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_SPRING_FEET_II): "W6: Spring Feet II - Top of Flag",
    (CheckKind.NORMAL_EXIT, _STAGE_SOLAR_ROLLER): "Special: Solar Roller - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_SOLAR_ROLLER): "Special: Solar Roller - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_SOLAR_ROLLER): "Special: Solar Roller - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_PETAL_ISLES_FLYING_BATTLESHIP): "PI: Petal Isles Flying Battleship - Normal Exit",
    (CheckKind.WONDER_SEED, _STAGE_PETAL_ISLES_FLYING_BATTLESHIP): "PI: Petal Isles Flying Battleship - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_GNAWSHER_LAIR): "PI: Gnawsher Lair - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_GNAWSHER_LAIR): "PI: Gnawsher Lair - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_GNAWSHER_LAIR): "PI: Gnawsher Lair - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_MAW_MAW_MOUTHFUL): "PI: Maw-Maw Mouthful - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_MAW_MAW_MOUTHFUL): "PI: Maw-Maw Mouthful - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_MAW_MAW_MOUTHFUL): "PI: Maw-Maw Mouthful - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_BOOSTING_SPIN_JUMP_I): "PI: Boosting Spin Jump I - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_BOOSTING_SPIN_JUMP_I): "PI: Boosting Spin Jump I - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_SPELUNKING): "PI: Spelunking! - Wonder Seed",
    (CheckKind.WONDER_SEED, _STAGE_PETAL_MEDDLE): "PI: Petal Meddle - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_WAY_OF_THE_GOOMBA): "Special: Way of the Goomba - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_WAY_OF_THE_GOOMBA): "Special: Way of the Goomba - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_WAY_OF_THE_GOOMBA): "Special: Way of the Goomba - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_MUNCHER_FIELDS): "PI: Muncher Fields - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_MUNCHER_FIELDS): "PI: Muncher Fields - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_MUNCHER_FIELDS): "PI: Muncher Fields - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_MISSILE_MEG_MAYHEM): "PI: Missile Meg Mayhem - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_MISSILE_MEG_MAYHEM): "PI: Missile Meg Mayhem - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_MISSILE_MEG_MAYHEM): "PI: Missile Meg Mayhem - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_HIGH_VOLTAGE_GAUNTLET): "PI: High-Voltage Gauntlet - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_HIGH_VOLTAGE_GAUNTLET): "PI: High-Voltage Gauntlet - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_HIGH_VOLTAGE_GAUNTLET): "PI: High-Voltage Gauntlet - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_EVADE_THE_SEEKER_BULLET_BILLS): "PI: Evade the Seeker Bullet Bills! - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_EVADE_THE_SEEKER_BULLET_BILLS): "PI: Evade the Seeker Bullet Bills! - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_EVADE_THE_SEEKER_BULLET_BILLS): "PI: Evade the Seeker Bullet Bills! - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_KNUCKLEFEST_BOWSER_S_BLAZING_BEATS): "PI: KnuckleFest Bowser's Blazing Beats - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_KNUCKLEFEST_BOWSER_S_BLAZING_BEATS): "PI: KnuckleFest Bowser's Blazing Beats - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_KNUCKLEFEST_BOWSER_S_BLAZING_BEATS): "PI: KnuckleFest Bowser's Blazing Beats - Wonder Seed",
    (CheckKind.PALACE_CLEAR, _STAGE_BOWSER_S_RAGE_STAGE): "PI: Bowser's Rage Stage - Royal Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_WONDER_GAUNTLET): "Special: Wonder Gauntlet - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_WONDER_GAUNTLET): "Special: Wonder Gauntlet - Top of Flag",
    (CheckKind.WONDER_SEED, _STAGE_WONDER_GAUNTLET): "Special: Wonder Gauntlet - Wonder Seed",
    (CheckKind.NORMAL_EXIT, _STAGE_BADGE_MARATHON): "Special: Badge Marathon - Normal Exit",
    (CheckKind.TOP_OF_FLAG, _STAGE_BADGE_MARATHON): "Special: Badge Marathon - Top of Flag",
    (CheckKind.NORMAL_EXIT, _STAGE_WONDER): "Special: WONDER? - Normal Exit",
}

# Badge AP checks.  Only badges *purchased at a Poplin Shop* are AP
# locations; badges handed out by courses / Badge Challenges are no
# longer checks (the apworld dropped their ``"<Badge> Obtained"``
# locations -- only the shop badges remain in data/locations.json).
# Course badges are still AP *items* (``_BADGES`` keeps all 24 so the
# grant/bitfield path still owns them, and the logic gates still need
# them) -- they're just not checks, so we don't map them to a location.
# A BADGE_ACQUIRED CheckEmitted for a course badge therefore resolves
# to ``None`` in ``lookup_name`` and is dropped before any LocationCheck
# goes out.  Keep this set in sync with the badge "Obtained" locations
# in data/locations.json.
#
# Item names (not location names): ``_BADGES`` carries the items.json
# spelling, including the bubble badge's "All Bubble Flower Badge"
# asymmetry (its location is "All Bubble Power Badge Obtained", patched
# by the override map below).
_SHOP_BADGE_ITEM_NAMES: Final[frozenset[str]] = frozenset({
    "Coin Reward Badge",
    "Add ! Blocks Badge",
    "Safety Bounce Badge",
    "Timed High Jump Badge",
    "Fast Dash Badge",
    "Coin Magnet Badge",
    "All Elephant Power Badge",
    "All Fire Power Badge",
    "All Bubble Flower Badge",
    "All Drill Power Badge",
})

_BADGE_LOCATION_NAME_OVERRIDES: Final[dict[str, str]] = {
    "All Bubble Flower Badge": "All Bubble Power Badge Obtained",
}


def is_checkable_badge(item_name: str) -> bool:
    """True if this badge AP item has a corresponding ``"<Badge>
    Obtained"`` AP location -- i.e. it's a shop-purchased badge.  Course
    /  Badge-Challenge badges return False: they're granted but not
    checked."""
    return item_name in _SHOP_BADGE_ITEM_NAMES


def _populate_badge_entries() -> None:
    for name, bit, _confidence in _BADGES:
        if name not in _SHOP_BADGE_ITEM_NAMES:
            continue  # course-granted badge: not an AP check
        loc = _BADGE_LOCATION_NAME_OVERRIDES.get(name, f"{name} Obtained")
        _TABLE[(CheckKind.BADGE_ACQUIRED, bit)] = loc


_populate_badge_entries()


# (world_no, npc_id, item_value) -> AP location name for SHOP_SEED checks.
#
# Schema (from the W1, W2, "W4 Secret" Poplin Shop captures 2026-05-25):
#   - The shop's identity is the (world_no, npc_id) pair carried by every
#     general_shop_result PlayReport.
#   - item_value is 0 for single-seed shops; multi-slot shops (only the
#     W4 Secret today) use item_value to distinguish their seeds.
#
# ★ AP world prefix → PlayReport world_no offset rule.  The apworld's
# location names use "W1:" / "PI:" / "W2:" / ... as progression labels.
# These do NOT match PlayReport ``world_no`` 1:1 — Petal Isles takes the
# PlayReport ``world_no=2`` slot between W1 and W2 (mirrors the SMBW
# engine's container-A 0x9f5ead3c world numbering — see CLAUDE.md
# "World index ordering" + switch-mod's kWorldValToBucket).  Mapping:
#
#     AP "W1"  → PlayReport world_no=1
#     AP "PI"  → PlayReport world_no=2
#     AP "W2"  → PlayReport world_no=3
#     AP "W3"  → PlayReport world_no=4
#     AP "W4"  → PlayReport world_no=5
#     AP "W5"  → PlayReport world_no=6
#     AP "W6"  → PlayReport world_no=7
#     AP "Special" → PlayReport world_no=9
#       (world_no=8 is "Castle"/Bowser, not a player overworld; the
#        Special-World jump from 7→9 was confirmed 2026-05-28 from a
#        live course_in PlayReport)
#
# Always use the PlayReport's world_no (from the bridge log's
# "general_shop_result → shop_seed at (world=X, npc=Y, slot=Z)" line)
# as the dict key; do NOT derive it from the AP prefix.
#
# Locations marked TODO have the apworld AP name pre-filled but no
# (world_no, npc_id) yet; lookup_name will return None and the bridge
# logs a debug line until the entry is filled in.


def pr_world_no_to_ap_world(world_no: int) -> int | None:
    """Inverse of the AP-prefix → PlayReport ``world_no`` offset rule
    documented above: map a PlayReport ``world_no`` back to the apworld's
    numbered world (1..6, matching ``open_world.WORLD_NUMBERS`` and the
    ``open_world_active`` slot_data list).

    Returns ``None`` for slots that are NOT one of the six numbered
    overworlds -- Petal Isles (``world_no=2``, the hub), Castle/Bowser
    (``world_no=8``), and the Special world (``world_no=9``).  Used by the
    open-world level-entry gate to decide whether a badge course belongs
    to a world the player is actually playing."""
    if world_no == 1:
        return 1
    if 3 <= world_no <= 7:
        return world_no - 1
    return None
_SHOP_SEED_TABLE: Final[dict[tuple[int, int, int], str]] = {
    # W1 Poplin Shop — captured 2026-05-25
    # (AP "W1" → PR world_no=1, npc_id=2; W1 overworld stage 3567658589)
    (1, 2, 0): "W1: Poplin Shop - Wonder Seed",

    # W2 Poplin Shop (Bottom) — captured 2026-05-25
    # (AP "W2" → PR world_no=3, npc_id=4; W2 overworld stage 956270015)
    (3, 4, 0): "W2: Poplin Shop (Bottom) - Wonder Seed",

    # W2 Poplin Shop (Top) — captured 2026-05-25 (same world_no as Bottom,
    # distinct npc_id=3; note npc_ids are arbitrary per-world indices and
    # do NOT correspond to a Top/Bottom ordering.)
    (3, 3, 0): "W2: Poplin Shop (Top) - Wonder Seed",

    # W3 Poplin Shop — captured 2026-05-25
    # (AP "W3" → PR world_no=4, npc_id=7; W3 overworld stage 2810861941)
    (4, 7, 0): "W3: Poplin Shop - Wonder Seed",

    # PI Poplin Shop (East) — captured 2026-05-25
    # (AP "PI" → PR world_no=2, npc_id=4; PI overworld stage 3108913375,
    # matches WORLD_RESULT_W1_TO_W2's next_stage_info.stage_key.)
    (2, 4, 0): "PI: Poplin Shop (East) - Wonder Seed",

    # W4 Poplin Shop (Bottom) — the regular (non-Secret) W4 shop.
    # Captured 2026-05-25: AP "W4" → PR world_no=5, npc_id=9.  Shares
    # the W4 overworld stage_key=4206506864 with the W4 Secret shop
    # (npc_id=5), distinguished by npc_id.
    (5, 9, 0): "W4: Poplin Shop (Bottom) - Wonder Seed",

    # W4 Poplin Shop (Secret) — 3 priced seeds at npc_id=5, captured
    # 2026-05-25 in shop-shelf order (the SMBW convention is
    # cheapest-first left-to-right):
    #   item_value=0 = leftmost shelf  → 30 Coins
    #   item_value=1 = middle shelf    → 100 Coins
    #   item_value=2 = rightmost shelf → 200 Coins
    # The 3 entries share the SHOP_SEED stage_key (5<<16)|5; dedup is
    # via state.emit_check's shop_slot sub_key so each priced seed
    # records its AP credit independently.
    (5, 5, 0): "W4: Poplin Shop (Secret) - Wonder Seed (30 Coins)",
    (5, 5, 1): "W4: Poplin Shop (Secret) - Wonder Seed (100 Coins)",
    (5, 5, 2): "W4: Poplin Shop (Secret) - Wonder Seed (200 Coins)",

    # NOTE on Poplin's Houses (PI Angler, W3 Master, W4 Sunbaked Desert,
    # W5 Loyal, W5 Tumble): houses are guaranteed NOT to use
    # general_shop_result (player confirmation 2026-05-25), so they're
    # not in this table.  When their room name + discriminator are
    # known, add a separate handler + table.  Strategy:
    #   - One W5 House visit reveals the room format and one of the two
    #     W5 houses' npc_id; the other W5 house follows by elimination.
    #   - PI/W3/W4 each have a single house in the apworld, so any
    #     house-event in those PR world_no values uniquely identifies
    #     them with no further captures.
}


# Wildcard fallback for SHOP_SEED: matches (world_no, item_value) when
# the exact (world_no, npc_id, item_value) key is NOT in
# _SHOP_SEED_TABLE.  Used for worlds where elimination uniquely
# identifies the AP location:
#
#   - PI (world_no=2): East is exact-mapped at (2, 4, 0).  The apworld
#     has exactly two PI Poplin Shops (East + West); since houses don't
#     fire general_shop_result, any other npc_id in PI is West.
#   - W5 (world_no=6): the apworld has exactly one W5 Poplin Shop; the
#     two W5 Houses are out via room-type filter.
#   - W6 (world_no=7): the apworld has exactly one W6 Poplin Shop;
#     no houses in W6.
#
# Order of lookup in ``lookup_name``: exact table first, then this
# wildcard table — so the W4 Secret triple's (5, 5, 0/1/2) entries
# still win over any W4 wildcard if one were ever added, and PI East's
# (2, 4, 0) wins over the PI West wildcard at (2, 0).
_SHOP_SEED_WILDCARD_TABLE: Final[dict[tuple[int, int], str]] = {
    (2, 0): "PI: Poplin Shop (West) - Wonder Seed",
    (6, 0): "W5: Poplin Shop - Wonder Seed",
    (7, 0): "W6: Poplin Shop - Wonder Seed",
}


# (stage_key, coin_index) -> AP location name for TEN_COIN checks.
# Every course with hidden 10-coin rooms has three "10 Coin" AP
# locations named #1/#2/#3 -- this includes the four palaces that ship
# them in locations.json (W1 Pipe-Rock Plateau, W2 Fluff-Puff Peaks,
# W4 Sunbaked Desert, W6 Deep Magma Bog).  The PlayReport
# ``big_flower_coin_course_in/out`` arrays carry per-course coin state
# at indices 0/1/2; whether those align with the apworld's #1/#2/#3
# numbering is unverified — see docs/m2.2-runbook.md
# "Open question: array index vs apworld # numbering" for the
# blind-mapping MVP choice (index N → #N+1).
_TEN_COIN_TABLE: Final[dict[tuple[int, int], str]] = {
    (_STAGE_WELCOME_TO_THE_FLOWER_KINGDOM, 0): "W1: Welcome to the Flower Kingdom! - 10 Coin #1",
    (_STAGE_WELCOME_TO_THE_FLOWER_KINGDOM, 1): "W1: Welcome to the Flower Kingdom! - 10 Coin #2",
    (_STAGE_WELCOME_TO_THE_FLOWER_KINGDOM, 2): "W1: Welcome to the Flower Kingdom! - 10 Coin #3",
    (_STAGE_PIRANHA_PLANTS_ON_PARADE, 0): "W1: Piranha Plants on Parade - 10 Coin #1",
    (_STAGE_PIRANHA_PLANTS_ON_PARADE, 1): "W1: Piranha Plants on Parade - 10 Coin #2",
    (_STAGE_PIRANHA_PLANTS_ON_PARADE, 2): "W1: Piranha Plants on Parade - 10 Coin #3",
    (_STAGE_SCRAM_SKEDADDLERS, 0): "W1: Scram, Skedaddlers! - 10 Coin #1",
    (_STAGE_SCRAM_SKEDADDLERS, 1): "W1: Scram, Skedaddlers! - 10 Coin #2",
    (_STAGE_SCRAM_SKEDADDLERS, 2): "W1: Scram, Skedaddlers! - 10 Coin #3",
    (_STAGE_BULRUSH_COMING_THROUGH, 0): "W1: Bulrush Coming Through! - 10 Coin #1",
    (_STAGE_BULRUSH_COMING_THROUGH, 1): "W1: Bulrush Coming Through! - 10 Coin #2",
    (_STAGE_BULRUSH_COMING_THROUGH, 2): "W1: Bulrush Coming Through! - 10 Coin #3",
    (_STAGE_HERE_COME_THE_HOPPOS, 0): "W1: Here Come the Hoppos - 10 Coin #1",
    (_STAGE_HERE_COME_THE_HOPPOS, 1): "W1: Here Come the Hoppos - 10 Coin #2",
    (_STAGE_HERE_COME_THE_HOPPOS, 2): "W1: Here Come the Hoppos - 10 Coin #3",
    (_STAGE_ROLLA_KOOPA_DERBY, 0): "W1: Rolla Koopa Derby - 10 Coin #1",
    (_STAGE_ROLLA_KOOPA_DERBY, 1): "W1: Rolla Koopa Derby - 10 Coin #2",
    (_STAGE_ROLLA_KOOPA_DERBY, 2): "W1: Rolla Koopa Derby - 10 Coin #3",
    (_STAGE_PARACHUTE_CAP_I, 0): "W1: Parachute Cap I - 10 Coin #1",
    (_STAGE_PARACHUTE_CAP_I, 1): "W1: Parachute Cap I - 10 Coin #2",
    (_STAGE_PARACHUTE_CAP_I, 2): "W1: Parachute Cap I - 10 Coin #3",
    (_STAGE_SWAMP_PIPE_CRAWL, 0): "W1: Swamp Pipe Crawl - 10 Coin #1",
    (_STAGE_SWAMP_PIPE_CRAWL, 1): "W1: Swamp Pipe Crawl - 10 Coin #2",
    (_STAGE_SWAMP_PIPE_CRAWL, 2): "W1: Swamp Pipe Crawl - 10 Coin #3",
    (_STAGE_ANGRY_SPIKES_AND_SINKIN_PIPES, 0): "W1: Angry Spikes and Sinkin' Pipes - 10 Coin #1",
    (_STAGE_ANGRY_SPIKES_AND_SINKIN_PIPES, 1): "W1: Angry Spikes and Sinkin' Pipes - 10 Coin #2",
    (_STAGE_ANGRY_SPIKES_AND_SINKIN_PIPES, 2): "W1: Angry Spikes and Sinkin' Pipes - 10 Coin #3",
    (_STAGE_BULRUSH_EXPRESS, 0): "W1: Bulrush Express - 10 Coin #1",
    (_STAGE_BULRUSH_EXPRESS, 1): "W1: Bulrush Express - 10 Coin #2",
    (_STAGE_BULRUSH_EXPRESS, 2): "W1: Bulrush Express - 10 Coin #3",
    (_STAGE_WALL_CLIMB_JUMP_I, 0): "W1: Wall-Climb Jump I - 10 Coin #1",
    (_STAGE_WALL_CLIMB_JUMP_I, 1): "W1: Wall-Climb Jump I - 10 Coin #2",
    (_STAGE_WALL_CLIMB_JUMP_I, 2): "W1: Wall-Climb Jump I - 10 Coin #3",
    (_STAGE_PIPE_ROCK_RUMBLE, 0): "W1: Pipe-Rock Rumble - 10 Coin #1",
    (_STAGE_PIPE_ROCK_RUMBLE, 1): "W1: Pipe-Rock Rumble - 10 Coin #2",
    (_STAGE_PIPE_ROCK_RUMBLE, 2): "W1: Pipe-Rock Rumble - 10 Coin #3",
    (_STAGE_SPROINGS_IN_THE_TWILIGHT_FOREST, 0): "W1: Sproings in the Twilight Forest - 10 Coin #1",
    (_STAGE_SPROINGS_IN_THE_TWILIGHT_FOREST, 1): "W1: Sproings in the Twilight Forest - 10 Coin #2",
    (_STAGE_SPROINGS_IN_THE_TWILIGHT_FOREST, 2): "W1: Sproings in the Twilight Forest - 10 Coin #3",
    (_STAGE_COSMIC_HOPPOS, 0): "W1: Cosmic Hoppos - 10 Coin #1",
    (_STAGE_COSMIC_HOPPOS, 1): "W1: Cosmic Hoppos - 10 Coin #2",
    (_STAGE_COSMIC_HOPPOS, 2): "W1: Cosmic Hoppos - 10 Coin #3",
    (_STAGE_JET_RUN_I, 0): "W1: Jet Run I - 10 Coin #1",
    (_STAGE_JET_RUN_I, 1): "W1: Jet Run I - 10 Coin #2",
    (_STAGE_JET_RUN_I, 2): "W1: Jet Run I - 10 Coin #3",
    (_STAGE_BOUNCE_BOUNCE_BOUNCE, 0): "Special: Bounce, Bounce, Bounce - 10 Coin #1",
    (_STAGE_BOUNCE_BOUNCE_BOUNCE, 1): "Special: Bounce, Bounce, Bounce - 10 Coin #2",
    (_STAGE_BOUNCE_BOUNCE_BOUNCE, 2): "Special: Bounce, Bounce, Bounce - 10 Coin #3",
    (_STAGE_LEAPING_SMACKEREL, 0): "PI: Leaping Smackerel - 10 Coin #1",
    (_STAGE_LEAPING_SMACKEREL, 1): "PI: Leaping Smackerel - 10 Coin #2",
    (_STAGE_LEAPING_SMACKEREL, 2): "PI: Leaping Smackerel - 10 Coin #3",
    (_STAGE_DOLPHIN_KICK_I, 0): "PI: Dolphin Kick I - 10 Coin #1",
    (_STAGE_DOLPHIN_KICK_I, 1): "PI: Dolphin Kick I - 10 Coin #2",
    (_STAGE_DOLPHIN_KICK_I, 2): "PI: Dolphin Kick I - 10 Coin #3",
    (_STAGE_ROBBIRD_COVE, 0): "PI: Robbird Cove - 10 Coin #1",
    (_STAGE_ROBBIRD_COVE, 1): "PI: Robbird Cove - 10 Coin #2",
    (_STAGE_ROBBIRD_COVE, 2): "PI: Robbird Cove - 10 Coin #3",
    (_STAGE_BLEWBIRD_ROOST, 0): "PI: Blewbird Roost - 10 Coin #1",
    (_STAGE_BLEWBIRD_ROOST, 1): "PI: Blewbird Roost - 10 Coin #2",
    (_STAGE_BLEWBIRD_ROOST, 2): "PI: Blewbird Roost - 10 Coin #3",
    (_STAGE_OUTMAWAY_VALLEY, 0): "W2: Outmaway Valley - 10 Coin #1",
    (_STAGE_OUTMAWAY_VALLEY, 1): "W2: Outmaway Valley - 10 Coin #2",
    (_STAGE_OUTMAWAY_VALLEY, 2): "W2: Outmaway Valley - 10 Coin #3",
    (_STAGE_POKIPEDE_PASS, 0): "W2: Pokipede Pass - 10 Coin #1",
    (_STAGE_POKIPEDE_PASS, 1): "W2: Pokipede Pass - 10 Coin #2",
    (_STAGE_POKIPEDE_PASS, 2): "W2: Pokipede Pass - 10 Coin #3",
    (_STAGE_WALL_CLIMB_JUMP_II, 0): "W2: Wall-Climb Jump II - 10 Coin #1",
    (_STAGE_WALL_CLIMB_JUMP_II, 1): "W2: Wall-Climb Jump II - 10 Coin #2",
    (_STAGE_WALL_CLIMB_JUMP_II, 2): "W2: Wall-Climb Jump II - 10 Coin #3",
    (_STAGE_CONDARTS_AWAY, 0): "W2: Condarts Away! - 10 Coin #1",
    (_STAGE_CONDARTS_AWAY, 1): "W2: Condarts Away! - 10 Coin #2",
    (_STAGE_CONDARTS_AWAY, 2): "W2: Condarts Away! - 10 Coin #3",
    (_STAGE_POLE_BLOCK_PASSAGE, 0): "W2: Pole Block Passage - 10 Coin #1",
    (_STAGE_POLE_BLOCK_PASSAGE, 1): "W2: Pole Block Passage - 10 Coin #2",
    (_STAGE_POLE_BLOCK_PASSAGE, 2): "W2: Pole Block Passage - 10 Coin #3",
    (_STAGE_JUMP_JUMP_JUMP, 0): "W2: Jump! Jump Jump! - 10 Coin #1",
    (_STAGE_JUMP_JUMP_JUMP, 1): "W2: Jump! Jump Jump! - 10 Coin #2",
    (_STAGE_JUMP_JUMP_JUMP, 2): "W2: Jump! Jump Jump! - 10 Coin #3",
    (_STAGE_FLOATING_HIGH_JUMP_I, 0): "W2: Floating High Jump I - 10 Coin #1",
    (_STAGE_FLOATING_HIGH_JUMP_I, 1): "W2: Floating High Jump I - 10 Coin #2",
    (_STAGE_FLOATING_HIGH_JUMP_I, 2): "W2: Floating High Jump I - 10 Coin #3",
    (_STAGE_FLUFF_PUFF_KERFUFF, 0): "W2: Fluff-Puff Kerfuff - 10 Coin #1",
    (_STAGE_FLUFF_PUFF_KERFUFF, 1): "W2: Fluff-Puff Kerfuff - 10 Coin #2",
    (_STAGE_FLUFF_PUFF_KERFUFF, 2): "W2: Fluff-Puff Kerfuff - 10 Coin #3",
    (_STAGE_SPRING_FEET_I, 0): "W2: Spring Feet I - 10 Coin #1",
    (_STAGE_SPRING_FEET_I, 1): "W2: Spring Feet I - 10 Coin #2",
    (_STAGE_SPRING_FEET_I, 2): "W2: Spring Feet I - 10 Coin #3",
    (_STAGE_CLIMB_TO_THE_BEAT, 0): "Special: Climb to the Beat - 10 Coin #1",
    (_STAGE_CLIMB_TO_THE_BEAT, 1): "Special: Climb to the Beat - 10 Coin #2",
    (_STAGE_CLIMB_TO_THE_BEAT, 2): "Special: Climb to the Beat - 10 Coin #3",
    (_STAGE_UP_N_DOWN_WITH_PUFFY_LIFTS, 0): "W2: Up 'n' Down with Puffy Lifts - 10 Coin #1",
    (_STAGE_UP_N_DOWN_WITH_PUFFY_LIFTS, 1): "W2: Up 'n' Down with Puffy Lifts - 10 Coin #2",
    (_STAGE_UP_N_DOWN_WITH_PUFFY_LIFTS, 2): "W2: Up 'n' Down with Puffy Lifts - 10 Coin #3",
    (_STAGE_FLUFF_PUFF_PEAKS_FLYING_BATTLESHIP, 0): "W2: Fluff-Puff Peaks Flying Battleship - 10 Coin #1",
    (_STAGE_FLUFF_PUFF_PEAKS_FLYING_BATTLESHIP, 1): "W2: Fluff-Puff Peaks Flying Battleship - 10 Coin #2",
    (_STAGE_FLUFF_PUFF_PEAKS_FLYING_BATTLESHIP, 2): "W2: Fluff-Puff Peaks Flying Battleship - 10 Coin #3",
    (_STAGE_COUNTDOWN_TO_DROP_DOWN, 0): "W2: Countdown to Drop Down - 10 Coin #1",
    (_STAGE_COUNTDOWN_TO_DROP_DOWN, 1): "W2: Countdown to Drop Down - 10 Coin #2",
    (_STAGE_COUNTDOWN_TO_DROP_DOWN, 2): "W2: Countdown to Drop Down - 10 Coin #3",
    (_STAGE_CRUISING_WITH_LINKING_LIFTS, 0): "W2: Cruising with Linking Lifts - 10 Coin #1",
    (_STAGE_CRUISING_WITH_LINKING_LIFTS, 1): "W2: Cruising with Linking Lifts - 10 Coin #2",
    (_STAGE_CRUISING_WITH_LINKING_LIFTS, 2): "W2: Cruising with Linking Lifts - 10 Coin #3",
    (_STAGE_DOLPHIN_KICK_II, 0): "PI: Dolphin Kick II - 10 Coin #1",
    (_STAGE_DOLPHIN_KICK_II, 1): "PI: Dolphin Kick II - 10 Coin #2",
    (_STAGE_DOLPHIN_KICK_II, 2): "PI: Dolphin Kick II - 10 Coin #3",
    (_STAGE_DOWNPOUR_UPROAR, 0): "PI: Downpour Uproar - 10 Coin #1",
    (_STAGE_DOWNPOUR_UPROAR, 1): "PI: Downpour Uproar - 10 Coin #2",
    (_STAGE_DOWNPOUR_UPROAR, 2): "PI: Downpour Uproar - 10 Coin #3",
    (_STAGE_THE_HOPPYCAT_TRIAL, 0): "W3: The Hoppycat Trial - 10 Coin #1",
    (_STAGE_THE_HOPPYCAT_TRIAL, 1): "W3: The Hoppycat Trial - 10 Coin #2",
    (_STAGE_THE_HOPPYCAT_TRIAL, 2): "W3: The Hoppycat Trial - 10 Coin #3",
    (_STAGE_THE_ANGLEFISH_TRIAL, 0): "W3: The Anglefish Trial - 10 Coin #1",
    (_STAGE_THE_ANGLEFISH_TRIAL, 1): "W3: The Anglefish Trial - 10 Coin #2",
    (_STAGE_THE_ANGLEFISH_TRIAL, 2): "W3: The Anglefish Trial - 10 Coin #3",
    (_STAGE_CROUCHING_HIGH_JUMP_I, 0): "W3: Crouching High Jump I - 10 Coin #1",
    (_STAGE_CROUCHING_HIGH_JUMP_I, 1): "W3: Crouching High Jump I - 10 Coin #2",
    (_STAGE_CROUCHING_HIGH_JUMP_I, 2): "W3: Crouching High Jump I - 10 Coin #3",
    (_STAGE_THE_MIDWAY_TRIAL, 0): "W3: The Midway Trial - 10 Coin #1",
    (_STAGE_THE_MIDWAY_TRIAL, 1): "W3: The Midway Trial - 10 Coin #2",
    (_STAGE_THE_MIDWAY_TRIAL, 2): "W3: The Midway Trial - 10 Coin #3",
    (_STAGE_THE_SHARP_TRIAL, 0): "W3: The Sharp Trial - 10 Coin #1",
    (_STAGE_THE_SHARP_TRIAL, 1): "W3: The Sharp Trial - 10 Coin #2",
    (_STAGE_THE_SHARP_TRIAL, 2): "W3: The Sharp Trial - 10 Coin #3",
    (_STAGE_THE_SUGARSTAR_TRIAL, 0): "W3: The Sugarstar Trial - 10 Coin #1",
    (_STAGE_THE_SUGARSTAR_TRIAL, 1): "W3: The Sugarstar Trial - 10 Coin #2",
    (_STAGE_THE_SUGARSTAR_TRIAL, 2): "W3: The Sugarstar Trial - 10 Coin #3",
    (_STAGE_THE_FINAL_TRIAL, 0): "W3: The Final Trial - 10 Coin #1",
    (_STAGE_THE_FINAL_TRIAL, 1): "W3: The Final Trial - 10 Coin #2",
    (_STAGE_THE_FINAL_TRIAL, 2): "W3: The Final Trial - 10 Coin #3",
    (_STAGE_TRIPLE_THREAT_DELUGE, 0): "Special: Triple Threat Deluge - 10 Coin #1",
    (_STAGE_TRIPLE_THREAT_DELUGE, 1): "Special: Triple Threat Deluge - 10 Coin #2",
    (_STAGE_TRIPLE_THREAT_DELUGE, 2): "Special: Triple Threat Deluge - 10 Coin #3",
    (_STAGE_JEWEL_BLOCK_CAVE, 0): "PI: Jewel-Block Cave - 10 Coin #1",
    (_STAGE_JEWEL_BLOCK_CAVE, 1): "PI: Jewel-Block Cave - 10 Coin #2",
    (_STAGE_JEWEL_BLOCK_CAVE, 2): "PI: Jewel-Block Cave - 10 Coin #3",
    (_STAGE_PIRANHA_PLANT_REPRISE, 0): "Special: Piranha Plant Reprise - 10 Coin #1",
    (_STAGE_PIRANHA_PLANT_REPRISE, 1): "Special: Piranha Plant Reprise - 10 Coin #2",
    (_STAGE_PIRANHA_PLANT_REPRISE, 2): "Special: Piranha Plant Reprise - 10 Coin #3",
    (_STAGE_ARMADS_ON_THE_ROLL, 0): "W4: Armads on the Roll - 10 Coin #1",
    (_STAGE_ARMADS_ON_THE_ROLL, 1): "W4: Armads on the Roll - 10 Coin #2",
    (_STAGE_ARMADS_ON_THE_ROLL, 2): "W4: Armads on the Roll - 10 Coin #3",
    (_STAGE_THE_DESERT_MYSTERY, 0): "W4: The Desert Mystery - 10 Coin #1",
    (_STAGE_THE_DESERT_MYSTERY, 1): "W4: The Desert Mystery - 10 Coin #2",
    (_STAGE_THE_DESERT_MYSTERY, 2): "W4: The Desert Mystery - 10 Coin #3",
    (_STAGE_ROLLING_BALL_HALL, 0): "W4: Rolling-Ball Hall - 10 Coin #1",
    (_STAGE_ROLLING_BALL_HALL, 1): "W4: Rolling-Ball Hall - 10 Coin #2",
    (_STAGE_ROLLING_BALL_HALL, 2): "W4: Rolling-Ball Hall - 10 Coin #3",
    (_STAGE_NINJI_JUMP_PARTY, 0): "W4: Ninji Jump Party - 10 Coin #1",
    (_STAGE_NINJI_JUMP_PARTY, 1): "W4: Ninji Jump Party - 10 Coin #2",
    (_STAGE_NINJI_JUMP_PARTY, 2): "W4: Ninji Jump Party - 10 Coin #3",
    (_STAGE_BLOOMPS_OF_THE_DESERT_SKIES, 0): "W4: Bloomps of the Desert Skies - 10 Coin #1",
    (_STAGE_BLOOMPS_OF_THE_DESERT_SKIES, 1): "W4: Bloomps of the Desert Skies - 10 Coin #2",
    (_STAGE_BLOOMPS_OF_THE_DESERT_SKIES, 2): "W4: Bloomps of the Desert Skies - 10 Coin #3",
    (_STAGE_VALLEY_FULLA_SNOOTLES, 0): "W4: Valley Fulla Snootles - 10 Coin #1",
    (_STAGE_VALLEY_FULLA_SNOOTLES, 1): "W4: Valley Fulla Snootles - 10 Coin #2",
    (_STAGE_VALLEY_FULLA_SNOOTLES, 2): "W4: Valley Fulla Snootles - 10 Coin #3",
    (_STAGE_COLOR_SWITCH_DUNGEON, 0): "W4: Color-Switch Dungeon - 10 Coin #1",
    (_STAGE_COLOR_SWITCH_DUNGEON, 1): "W4: Color-Switch Dungeon - 10 Coin #2",
    (_STAGE_COLOR_SWITCH_DUNGEON, 2): "W4: Color-Switch Dungeon - 10 Coin #3",
    (_STAGE_SECRETS_OF_SHOVA_MANSION, 0): "W4: Secrets of Shova Mansion - 10 Coin #1",
    (_STAGE_SECRETS_OF_SHOVA_MANSION, 1): "W4: Secrets of Shova Mansion - 10 Coin #2",
    (_STAGE_SECRETS_OF_SHOVA_MANSION, 2): "W4: Secrets of Shova Mansion - 10 Coin #3",
    (_STAGE_FLIGHT_OF_THE_BLOOMPS, 0): "W4: Flight of the Bloomps - 10 Coin #1",
    (_STAGE_FLIGHT_OF_THE_BLOOMPS, 1): "W4: Flight of the Bloomps - 10 Coin #2",
    (_STAGE_FLIGHT_OF_THE_BLOOMPS, 2): "W4: Flight of the Bloomps - 10 Coin #3",
    (_STAGE_PARACHUTE_CAP_II, 0): "W4: Parachute Cap II - 10 Coin #1",
    (_STAGE_PARACHUTE_CAP_II, 1): "W4: Parachute Cap II - 10 Coin #2",
    (_STAGE_PARACHUTE_CAP_II, 2): "W4: Parachute Cap II - 10 Coin #3",
    (_STAGE_CROUCHING_HIGH_JUMP_II, 0): "W4: Crouching High Jump II - 10 Coin #1",
    (_STAGE_CROUCHING_HIGH_JUMP_II, 1): "W4: Crouching High Jump II - 10 Coin #2",
    (_STAGE_CROUCHING_HIGH_JUMP_II, 2): "W4: Crouching High Jump II - 10 Coin #3",
    (_STAGE_INVISIBILITY_I, 0): "W4: Invisibility I - 10 Coin #1",
    (_STAGE_INVISIBILITY_I, 1): "W4: Invisibility I - 10 Coin #2",
    (_STAGE_INVISIBILITY_I, 2): "W4: Invisibility I - 10 Coin #3",
    (_STAGE_SUNBAKED_SKIRMISH, 0): "W4: Sunbaked Skirmish - 10 Coin #1",
    (_STAGE_SUNBAKED_SKIRMISH, 1): "W4: Sunbaked Skirmish - 10 Coin #2",
    (_STAGE_SUNBAKED_SKIRMISH, 2): "W4: Sunbaked Skirmish - 10 Coin #3",
    (_STAGE_POLE_BLOCK_ALLURE, 0): "Special: Pole Block Allure - 10 Coin #1",
    (_STAGE_POLE_BLOCK_ALLURE, 1): "Special: Pole Block Allure - 10 Coin #2",
    (_STAGE_POLE_BLOCK_ALLURE, 2): "Special: Pole Block Allure - 10 Coin #3",
    (_STAGE_UPSHROOM_DOWNSHROOM, 0): "W5: Upshroom Downshroom - 10 Coin #1",
    (_STAGE_UPSHROOM_DOWNSHROOM, 1): "W5: Upshroom Downshroom - 10 Coin #2",
    (_STAGE_UPSHROOM_DOWNSHROOM, 2): "W5: Upshroom Downshroom - 10 Coin #3",
    (_STAGE_TAILY_S_TOXIC_POND, 0): "W5: Taily's Toxic Pond - 10 Coin #1",
    (_STAGE_TAILY_S_TOXIC_POND, 1): "W5: Taily's Toxic Pond - 10 Coin #2",
    (_STAGE_TAILY_S_TOXIC_POND, 2): "W5: Taily's Toxic Pond - 10 Coin #3",
    (_STAGE_LIGHT_SWITCH_MANSION, 0): "W5: Light-Switch Mansion - 10 Coin #1",
    (_STAGE_LIGHT_SWITCH_MANSION, 1): "W5: Light-Switch Mansion - 10 Coin #2",
    (_STAGE_LIGHT_SWITCH_MANSION, 2): "W5: Light-Switch Mansion - 10 Coin #3",
    (_STAGE_BEWARE_OF_THE_RIFTS, 0): "W5: Beware of the Rifts - 10 Coin #1",
    (_STAGE_BEWARE_OF_THE_RIFTS, 1): "W5: Beware of the Rifts - 10 Coin #2",
    (_STAGE_BEWARE_OF_THE_RIFTS, 2): "W5: Beware of the Rifts - 10 Coin #3",
    (_STAGE_WUBBA_RUINS, 0): "W5: Wubba Ruins - 10 Coin #1",
    (_STAGE_WUBBA_RUINS, 1): "W5: Wubba Ruins - 10 Coin #2",
    (_STAGE_WUBBA_RUINS, 2): "W5: Wubba Ruins - 10 Coin #3",
    (_STAGE_SWAYING_RUINS, 0): "W5: Swaying Ruins - 10 Coin #1",
    (_STAGE_SWAYING_RUINS, 1): "W5: Swaying Ruins - 10 Coin #2",
    (_STAGE_SWAYING_RUINS, 2): "W5: Swaying Ruins - 10 Coin #3",
    (_STAGE_GRAPPLING_VINE_I, 0): "W5: Grappling Vine I - 10 Coin #1",
    (_STAGE_GRAPPLING_VINE_I, 1): "W5: Grappling Vine I - 10 Coin #2",
    (_STAGE_GRAPPLING_VINE_I, 2): "W5: Grappling Vine I - 10 Coin #3",
    (_STAGE_FUNGI_FUNK, 0): "W5: Fungi Funk - 10 Coin #1",
    (_STAGE_FUNGI_FUNK, 1): "W5: Fungi Funk - 10 Coin #2",
    (_STAGE_FUNGI_FUNK, 2): "W5: Fungi Funk - 10 Coin #3",
    (_STAGE_POISON_RUINS, 0): "W5: Poison Ruins - 10 Coin #1",
    (_STAGE_POISON_RUINS, 1): "W5: Poison Ruins - 10 Coin #2",
    (_STAGE_POISON_RUINS, 2): "W5: Poison Ruins - 10 Coin #3",
    (_STAGE_DANGEROUS_DONUT_RIDE, 0): "Special: Dangerous Donut Ride - 10 Coin #1",
    (_STAGE_DANGEROUS_DONUT_RIDE, 1): "Special: Dangerous Donut Ride - 10 Coin #2",
    (_STAGE_DANGEROUS_DONUT_RIDE, 2): "Special: Dangerous Donut Ride - 10 Coin #3",
    (_STAGE_WHERE_THE_RRRUMBAS_RULE, 0): "W6: Where the Rrrumbas Rule - 10 Coin #1",
    (_STAGE_WHERE_THE_RRRUMBAS_RULE, 1): "W6: Where the Rrrumbas Rule - 10 Coin #2",
    (_STAGE_WHERE_THE_RRRUMBAS_RULE, 2): "W6: Where the Rrrumbas Rule - 10 Coin #3",
    (_STAGE_RAARGHS_IN_THE_RUINS, 0): "W6: Raarghs in the Ruins - 10 Coin #1",
    (_STAGE_RAARGHS_IN_THE_RUINS, 1): "W6: Raarghs in the Ruins - 10 Coin #2",
    (_STAGE_RAARGHS_IN_THE_RUINS, 2): "W6: Raarghs in the Ruins - 10 Coin #3",
    (_STAGE_PULL_TURN_BURN, 0): "W6: Pull, Turn, Burn - 10 Coin #1",
    (_STAGE_PULL_TURN_BURN, 1): "W6: Pull, Turn, Burn - 10 Coin #2",
    (_STAGE_PULL_TURN_BURN, 2): "W6: Pull, Turn, Burn - 10 Coin #3",
    (_STAGE_DEEP_MAGMA_BOG_FLYING_BATTLESHIP, 0): "W6: Deep Magma Bog Flying Battleship - 10 Coin #1",
    (_STAGE_DEEP_MAGMA_BOG_FLYING_BATTLESHIP, 1): "W6: Deep Magma Bog Flying Battleship - 10 Coin #2",
    (_STAGE_DEEP_MAGMA_BOG_FLYING_BATTLESHIP, 2): "W6: Deep Magma Bog Flying Battleship - 10 Coin #3",
    (_STAGE_HOT_HOT_HOT, 0): "W6: Hot-Hot Hot! - 10 Coin #1",
    (_STAGE_HOT_HOT_HOT, 1): "W6: Hot-Hot Hot! - 10 Coin #2",
    (_STAGE_HOT_HOT_HOT, 2): "W6: Hot-Hot Hot! - 10 Coin #3",
    (_STAGE_WAVY_RIDE_THROUGH_THE_MAGMA_TUBE, 0): "W6: Wavy Ride through the Magma Tube - 10 Coin #1",
    (_STAGE_WAVY_RIDE_THROUGH_THE_MAGMA_TUBE, 1): "W6: Wavy Ride through the Magma Tube - 10 Coin #2",
    (_STAGE_WAVY_RIDE_THROUGH_THE_MAGMA_TUBE, 2): "W6: Wavy Ride through the Magma Tube - 10 Coin #3",
    (_STAGE_DRAGON_BONEYARD, 0): "W6: Dragon Boneyard - 10 Coin #1",
    (_STAGE_DRAGON_BONEYARD, 1): "W6: Dragon Boneyard - 10 Coin #2",
    (_STAGE_DRAGON_BONEYARD, 2): "W6: Dragon Boneyard - 10 Coin #3",
    (_STAGE_FLOATING_HIGH_JUMP_II, 0): "W6: Floating High Jump II - 10 Coin #1",
    (_STAGE_FLOATING_HIGH_JUMP_II, 1): "W6: Floating High Jump II - 10 Coin #2",
    (_STAGE_FLOATING_HIGH_JUMP_II, 2): "W6: Floating High Jump II - 10 Coin #3",
    (_STAGE_BOOSTING_SPIN_JUMP_II, 0): "W6: Boosting Spin Jump II - 10 Coin #1",
    (_STAGE_BOOSTING_SPIN_JUMP_II, 1): "W6: Boosting Spin Jump II - 10 Coin #2",
    (_STAGE_BOOSTING_SPIN_JUMP_II, 2): "W6: Boosting Spin Jump II - 10 Coin #3",
    (_STAGE_GRAPPLING_VINE_II, 0): "W6: Grappling Vine II - 10 Coin #1",
    (_STAGE_GRAPPLING_VINE_II, 1): "W6: Grappling Vine II - 10 Coin #2",
    (_STAGE_GRAPPLING_VINE_II, 2): "W6: Grappling Vine II - 10 Coin #3",
    (_STAGE_MAGMA_FLARE_UP, 0): "W6: Magma Flare-Up - 10 Coin #1",
    (_STAGE_MAGMA_FLARE_UP, 1): "W6: Magma Flare-Up - 10 Coin #2",
    (_STAGE_MAGMA_FLARE_UP, 2): "W6: Magma Flare-Up - 10 Coin #3",
    (_STAGE_JET_RUN_II, 0): "W6: Jet Run II - 10 Coin #1",
    (_STAGE_JET_RUN_II, 1): "W6: Jet Run II - 10 Coin #2",
    (_STAGE_JET_RUN_II, 2): "W6: Jet Run II - 10 Coin #3",
    (_STAGE_INVISIBILITY_II, 0): "W6: Invisibility II - 10 Coin #1",
    (_STAGE_INVISIBILITY_II, 1): "W6: Invisibility II - 10 Coin #2",
    (_STAGE_INVISIBILITY_II, 2): "W6: Invisibility II - 10 Coin #3",
    (_STAGE_SPRING_FEET_II, 0): "W6: Spring Feet II - 10 Coin #1",
    (_STAGE_SPRING_FEET_II, 1): "W6: Spring Feet II - 10 Coin #2",
    (_STAGE_SPRING_FEET_II, 2): "W6: Spring Feet II - 10 Coin #3",
    (_STAGE_SOLAR_ROLLER, 0): "Special: Solar Roller - 10 Coin #1",
    (_STAGE_SOLAR_ROLLER, 1): "Special: Solar Roller - 10 Coin #2",
    (_STAGE_SOLAR_ROLLER, 2): "Special: Solar Roller - 10 Coin #3",
    (_STAGE_PETAL_ISLES_FLYING_BATTLESHIP, 0): "PI: Petal Isles Flying Battleship - 10 Coin #1",
    (_STAGE_PETAL_ISLES_FLYING_BATTLESHIP, 1): "PI: Petal Isles Flying Battleship - 10 Coin #2",
    (_STAGE_PETAL_ISLES_FLYING_BATTLESHIP, 2): "PI: Petal Isles Flying Battleship - 10 Coin #3",
    (_STAGE_GNAWSHER_LAIR, 0): "PI: Gnawsher Lair - 10 Coin #1",
    (_STAGE_GNAWSHER_LAIR, 1): "PI: Gnawsher Lair - 10 Coin #2",
    (_STAGE_GNAWSHER_LAIR, 2): "PI: Gnawsher Lair - 10 Coin #3",
    (_STAGE_MAW_MAW_MOUTHFUL, 0): "PI: Maw-Maw Mouthful - 10 Coin #1",
    (_STAGE_MAW_MAW_MOUTHFUL, 1): "PI: Maw-Maw Mouthful - 10 Coin #2",
    (_STAGE_MAW_MAW_MOUTHFUL, 2): "PI: Maw-Maw Mouthful - 10 Coin #3",
    (_STAGE_BOOSTING_SPIN_JUMP_I, 0): "PI: Boosting Spin Jump I - 10 Coin #1",
    (_STAGE_BOOSTING_SPIN_JUMP_I, 1): "PI: Boosting Spin Jump I - 10 Coin #2",
    (_STAGE_BOOSTING_SPIN_JUMP_I, 2): "PI: Boosting Spin Jump I - 10 Coin #3",
    (_STAGE_PETAL_MEDDLE, 0): "PI: Petal Meddle - 10 Coin #1",
    (_STAGE_PETAL_MEDDLE, 1): "PI: Petal Meddle - 10 Coin #2",
    (_STAGE_PETAL_MEDDLE, 2): "PI: Petal Meddle - 10 Coin #3",
    (_STAGE_WAY_OF_THE_GOOMBA, 0): "Special: Way of the Goomba - 10 Coin #1",
    (_STAGE_WAY_OF_THE_GOOMBA, 1): "Special: Way of the Goomba - 10 Coin #2",
    (_STAGE_WAY_OF_THE_GOOMBA, 2): "Special: Way of the Goomba - 10 Coin #3",
    (_STAGE_MUNCHER_FIELDS, 0): "PI: Muncher Fields - 10 Coin #1",
    (_STAGE_MUNCHER_FIELDS, 1): "PI: Muncher Fields - 10 Coin #2",
    (_STAGE_MUNCHER_FIELDS, 2): "PI: Muncher Fields - 10 Coin #3",
    (_STAGE_MISSILE_MEG_MAYHEM, 0): "PI: Missile Meg Mayhem - 10 Coin #1",
    (_STAGE_MISSILE_MEG_MAYHEM, 1): "PI: Missile Meg Mayhem - 10 Coin #2",
    (_STAGE_MISSILE_MEG_MAYHEM, 2): "PI: Missile Meg Mayhem - 10 Coin #3",
    (_STAGE_HIGH_VOLTAGE_GAUNTLET, 0): "PI: High-Voltage Gauntlet - 10 Coin #1",
    (_STAGE_HIGH_VOLTAGE_GAUNTLET, 1): "PI: High-Voltage Gauntlet - 10 Coin #2",
    (_STAGE_HIGH_VOLTAGE_GAUNTLET, 2): "PI: High-Voltage Gauntlet - 10 Coin #3",
    (_STAGE_EVADE_THE_SEEKER_BULLET_BILLS, 0): "PI: Evade the Seeker Bullet Bills! - 10 Coin #1",
    (_STAGE_EVADE_THE_SEEKER_BULLET_BILLS, 1): "PI: Evade the Seeker Bullet Bills! - 10 Coin #2",
    (_STAGE_EVADE_THE_SEEKER_BULLET_BILLS, 2): "PI: Evade the Seeker Bullet Bills! - 10 Coin #3",
    (_STAGE_KNUCKLEFEST_BOWSER_S_BLAZING_BEATS, 0): "PI: KnuckleFest Bowser's Blazing Beats - 10 Coin #1",
    (_STAGE_KNUCKLEFEST_BOWSER_S_BLAZING_BEATS, 1): "PI: KnuckleFest Bowser's Blazing Beats - 10 Coin #2",
    (_STAGE_KNUCKLEFEST_BOWSER_S_BLAZING_BEATS, 2): "PI: KnuckleFest Bowser's Blazing Beats - 10 Coin #3",
    (_STAGE_WONDER_GAUNTLET, 0): "Special: Wonder Gauntlet - 10 Coin #1",
    (_STAGE_WONDER_GAUNTLET, 1): "Special: Wonder Gauntlet - 10 Coin #2",
    (_STAGE_WONDER_GAUNTLET, 2): "Special: Wonder Gauntlet - 10 Coin #3",
    (_STAGE_BADGE_MARATHON, 0): "Special: Badge Marathon - 10 Coin #1",
    (_STAGE_BADGE_MARATHON, 1): "Special: Badge Marathon - 10 Coin #2",
    (_STAGE_BADGE_MARATHON, 2): "Special: Badge Marathon - 10 Coin #3",
    (_STAGE_PIPE_ROCK_PLATEAU_PALACE, 0): "W1: Pipe-Rock Plateau Palace - 10 Coin #1",
    (_STAGE_PIPE_ROCK_PLATEAU_PALACE, 1): "W1: Pipe-Rock Plateau Palace - 10 Coin #2",
    (_STAGE_PIPE_ROCK_PLATEAU_PALACE, 2): "W1: Pipe-Rock Plateau Palace - 10 Coin #3",
    (_STAGE_FLUFF_PUFF_PEAKS_PALACE, 0): "W2: Fluff-Puff Peaks Palace - 10 Coin #1",
    (_STAGE_FLUFF_PUFF_PEAKS_PALACE, 1): "W2: Fluff-Puff Peaks Palace - 10 Coin #2",
    (_STAGE_FLUFF_PUFF_PEAKS_PALACE, 2): "W2: Fluff-Puff Peaks Palace - 10 Coin #3",
    (_STAGE_SUNBAKED_DESERT_PALACE, 0): "W4: Sunbaked Desert Palace - 10 Coin #1",
    (_STAGE_SUNBAKED_DESERT_PALACE, 1): "W4: Sunbaked Desert Palace - 10 Coin #2",
    (_STAGE_SUNBAKED_DESERT_PALACE, 2): "W4: Sunbaked Desert Palace - 10 Coin #3",
    (_STAGE_DEEP_MAGMA_BOG_PALACE, 0): "W6: Deep Magma Bog Palace - 10 Coin #1",
    (_STAGE_DEEP_MAGMA_BOG_PALACE, 1): "W6: Deep Magma Bog Palace - 10 Coin #2",
    (_STAGE_DEEP_MAGMA_BOG_PALACE, 2): "W6: Deep Magma Bog Palace - 10 Coin #3",
}
# ---- end generated ----



def lookup_name(check: CheckEmitted) -> str | None:
    """Resolve a CheckEmitted to its canonical AP location name.

    Returns ``None`` when no mapping exists; the caller (ap_client)
    should log + drop.  Missing entries are normal early in M4 (most
    courses haven't been mapped yet) and should NOT cascade into an AP
    error -- the bridge stays connected and the player just doesn't
    get credit for the un-mapped course until the table extends.
    """
    if check.kind == CheckKind.TEN_COIN:
        idx = int(check.metadata.get("coin_index", 0))
        name = _TEN_COIN_TABLE.get((check.stage_key, idx))
        if name is None:
            log.debug(
                "location_table: no AP location for ten_coin stage_key=%d index=%d",
                check.stage_key, idx)
        return name

    if check.kind == CheckKind.SHOP_SEED:
        world_no = int(check.metadata.get("world_no", 0))
        npc_id = int(check.metadata.get("npc_id", 0))
        item_value = int(check.metadata.get("item_value", 0))
        # Exact match wins.
        name = _SHOP_SEED_TABLE.get((world_no, npc_id, item_value))
        if name is not None:
            return name
        # Wildcard fallback for worlds where elimination uniquely
        # identifies the AP location (PI West, W5 Poplin, W6 Poplin).
        name = _SHOP_SEED_WILDCARD_TABLE.get((world_no, item_value))
        if name is None:
            log.debug(
                "location_table: no AP location for shop_seed "
                "(world=%d, npc=%d, item_value=%d) — add an entry to "
                "_SHOP_SEED_TABLE or _SHOP_SEED_WILDCARD_TABLE in "
                "location_table.py", world_no, npc_id, item_value)
        return name

    name = _TABLE.get((check.kind, check.stage_key))
    if name is None:
        log.debug(
            "location_table: no AP location for kind=%s stage_key=%d",
            check.kind.value, check.stage_key)
    return name
